devlooped/moq

- Source/InterceptorStrategies.cs
- UnitTests/Regressions/IssueReportsFixture.cs
Fix: #128 NotImplementedException DynamicProxy2 error when CallBase = true  while mocking interfaces
> Fix: #128 NotImplementedException DynamicProxy2 error when CallBase = true 

- Source/Match.cs
- UnitTests/MatchersFixture.cs
This fixes issue #90.
The problem was that `Matches()` has to cast its input to the type parameter `T` in order to call the `Condition` function.
Since `T` is a reference type, it does not accept nulls and throws a `NullReferenceException` at the site of the cast.
We get around this by treating value types as a special case inside `Matches`. If `T` is a value type and the input is null, it clearly doesn't match (since value types are not nullable).
> Fix NullReferenceException when passing null to a nullable argument but trying to match it with a non-nullable IsAny.

- Source/Extensions.cs
- UnitTests/Regressions/IssueReportsFixture.cs
Fixes #176 
Updates the ICallContext.Format extension method to include generic parameter information for non-property method calls.
> Add generic parameter type informat to exception text.

- Source/IInterceptStrategy.cs
- Source/MockExtensions.cs
- UnitTests/ExtensionsFixture.cs
This change adds `MockExtensions.Reset(Mock)` that completely resets the mock by removing all expectations and all actual invocations.
**Use case:**
Mocking singleton-lifetime object in integration tests where it is not possible to reset application state completely between tests -- so the mock instance can potentially be cached in other singleton services and cannot be replaced with a new mock.
> Added MockExtensions.Reset() to clear mock state (expectations+invocations)

- Source/Match.cs
- UnitTests/Regressions/IssueReportsFixture.cs
In the case where a null is passed and a value type is expected, allow a match where the value type is an instance of Nullable<T>.
> Issue 184: allow null to match nullable value types

- Source.Silverlight/Moq.Silverlight.csproj
- Source.Silverlight/packages.config
- Source/EmptyDefaultValueProvider.cs
- Source/ReturnsExtensions.cs
- UnitTests.Silverlight/Moq.Silverlight.Tests.csproj
- UnitTests.Silverlight/packages.config
- UnitTests/EmptyDefaultValueProviderFixture.cs
Per discussion in #66, Silverlight 4 support was dropped and added TPL Task support to SL5 version. #70 just disabled TPL Task support for Silverlifht version, this PR re-enable it.
> Make TPL code Silverlight 5 compatible

- Source/Mock.Generic.xdoc
- Source/Protected/IProtectedMock.cs
The [School House Rock](https://www.youtube.com/watch?v=ODGA7ssL-6g) spelling is the correct one. AFAIK, omitting the "c" isn't a valid alternative spelling. Ignore this PR if I'm wrong, though. Also, ignore the line-ending and end of file revisions. They're artifacts of GitHub's in-page editor.
> Saturday morning cartoon version of "conjunction"

- Source.Silverlight/packages.config
- Source/Moq.csproj
- Source/packages.config
- UnitTests.Silverlight/packages.config
- UnitTests/Moq.Tests.csproj
- UnitTests/packages.config
fixing the message of the exception thrown when mocking an internal
interface from an assembly not marked with [assembly:
InternalsVisibleTo("DynamicProxyGenAssembly2")]
> upgrading to Castle.Core 3.3.3

- Source/AsInterface.cs
- Source/Mock.cs
- Source/MockDefaultValueProvider.cs
Fixed issue #205 with the replacement of Dictionary type with
ConcurrentDictionary for InnerMocks property and using its GetOrAdd
method in MockDefaultValueProvider for making it thread-safe.
> Fix for issue #205 (Thread safety issue: race condition in MockDefaultValueProvider)

- Source/Proxy/CastleProxyFactory.cs
- UnitTests/MockedDelegatesFixture.cs
The out parameter of delegate mock was handled as same as ref parameter of method mock, because `ParameterInfo.Attributes` wasn't copied when creating delegate proxy.
> Fix the out parameter issue of delegate mock

- Source/Interceptor.cs
- UnitTests/Regressions/IssueReportsFixture.cs
This should fix #252.
The problem was in how hash code was calculated for `ExpressionKey` objects: expression keys with the same values but in a different order would have the same hash code, so that `calls.ContainsKey(key)' would think that the key already existed in the dictionary.
I modified the `GetHashCode()` function in the `ExpressionKey` class to fix this. And added a unit test in `IssueReportsFixture.cs`.
> Fixed setup issues when specifying the same parameters in a different order (issue #252)

- Source/Mock.cs
I tend to write a method that does multiple verifications a lot, it saves a few lines:
```
mock1.VerifyAll();
mock2.VerifyAll();
mock3.VerifyAll();
// Versus
Mock.VerifyAll(mock1, mock2, mock3);
```
> VerityMocks and VerifyAllMocks Static Helper Methods

- Source/Capture.cs
- Source/CaptureMatch.cs
- Source/Match.cs
- Source/Moq.csproj
- UnitTests/CaptureFixture.cs
- UnitTests/CaptureMatchFixture.cs
- UnitTests/Moq.Tests.csproj
It is frequently required to capture a mock parameter to perform complex assertions. Parameter capture is [a regular request from new Moq users](https://www.google.com/#q=moq+capture+argument).
It can be done with setups and callbacks, but the syntax can be tricky, especially for methods with many parameters.
This helper class simplifies parameter capture:
```cs
// Arrange
var capture = new MockCapture<string>();
mock.Setup(x => x.DoSomething(capture.CaptureAny()));
// Act
// ...
// Assert
Assert.Equal("World!", capture.Last);
```
> Add an helper class to simplify parameter capture

- Source/Extensions.cs
- Source/Mock.cs
- UnitTests/VerifyFixture.cs
There's a couple cases of using Verify that don't print very nice values when they fail. I've attempted to resolve a couple of these. 
1. parameter values that are arrays print as "System.String[]" instead of printing out and joining into a comma delimited list
2. setup and verify calls shown in exception messages display the variables referenced and not the values of those variables
Tests have been written/updated for these cases
> Exceptions using Verify for specific calls should include actual values

- Source/InterceptorStrategies.cs
- Source/Proxy/CastleProxyFactory.cs
- Source/Proxy/ProxyGenerationHelpers.cs
- UnitTests/MockFixture.cs
- int object.GetHashCode()
- bool object.Equals(object obj)
- string object.ToString()
This fixes #248.
> Allow for class mocks and interface mocks to mock System.Object methods

- Source/Interceptor.cs
- Source/InterceptorStrategies.cs
- UnitTests/Regressions/IssueReportsFixture.cs
Even in strict mode if none of them were set up. Fixes #273 and closes #248.
> `System.Object` methods should always work.

- Source/InterceptorStrategies.cs
- UnitTests/Regressions/IssueReportsFixture.cs
> Fixed `InterceptObjectMethodsMixin` to properly check for `System.Object` methods

- Source/Interceptor.cs
- Source/MockExtensions.cs
- UnitTests/ExtensionsFixture.cs
This should fix https://github.com/Moq/moq4/issues/220
The issue was that the calls in the interceptor were not cleared when reset was called.
> Moq Reset should clear all existing calls in the interceptor

- Moq.nuspec
The net45 project still depends on 3.3.3
> Fix Castle.Core dependency version

- Source/InterceptorStrategies.cs
- Source/Mock.Generic.cs
- Source/Mock.cs
- UnitTests/Regressions/IssueReportsFixture.cs
The ImplementedInterfaces list on Mock contains the public interfaces of our mocked type, the internally defined IMocked<T> type, and anything else added to the mock via calls to As<T>.  When looking for events, only the last of these (and the concrete mocked type) should be looked at.
Previously the assumption was that ImplementedInterfaces' first entry was the IMocked<T> type, and that the rest were always needed.  This meant the first entry in that list could be skipped, and the rest were always taken.  After 162a54379026a42bbc746335d63316819d078b56 added more interfaces to the list, however, this logic needs to change to count all internally implemented entries in the list and skip them all.
Fixing this will fix #228 which was caused when the EventInfo from an interface was …
> Fix for issue #228: Events not raised on mocked type with multiple interfaces

- Source/ReturnsExtensions.Generated.cs
- Source/ReturnsExtensions.cs
- Source/ReturnsExtensions.tt
- UnitTests/GeneratedReturnsExtensionsFixture.cs
- UnitTests/Moq.Tests.csproj
- UnitTests/ReturnsExtensionsFixture.cs
- `ReturnsAsync()` overload implementation
- Summary standardization for all `ReturnsAsync()` and `ThrowsAsync()` overloads
- Unit tests for lazy evaluation behavior
- New unit test fixture for _GeneratedReturnsExtensions_
> ReturnsAsync() lazy evaluation issue fix #303

- Moq.nuspec
- Source.NetCore/project.json
- Source/project.json
- UnitTests.NetCore/Moq.NetCore.Tests/project.json
- UnitTests/project.json
- global.json
- wrap/Moq/project.json
@kzu 
Any plan to get a non-pre release out?
After VS 2017 RTM, we can try switching to the new .csproj for both .NET Full and .NET Core.
> Upgrade Castle.Core dependency to 4.0.0

- Source/Mock.Generic.xdoc
Before: 
`Specifies a setup on the mocked type for a call to to a void method.`
After: 
`Specifies a setup on the mocked type for a call to a void method.`
> Fix typo in summary of Mock<T>.Setup docs

- Source/Mock.xdoc
> Fixing documentation typo on Verifiable() usage.

- Source/Extensions.cs
- Source/Protected/ProtectedMock.cs
The bug was introduced when replacing the `Type.GetMethod(...)` call
to the overload with a `Type[]` parameter since that overload is not
supported in .NET CORE.  The correct behavior should be checking for
compatible argument types, instead of strict matching argument types.
Fixes #334 and the test failure in recent build.
> Fix bug in HasMatchingParameterTypes

- Source/Mock.Generic.xdoc
This fixes #260 (4&times; duplicated word "to" in `Source/Mock.Generic.xdoc`).
> Docs: Fix 4 typos (fixes #260)

- UnitTests/ReturnsExtensionsFixture.cs
One unit tests uses `System.IO.InternalBufferOverflowException` as a placeholder. This type does not exist in .NET Standard 1.3 (it looks like it will be reintroduced with .NET Standard 2.0 in the `System.IO.FileSystem.Watcher` package) and so the .NET Standard build fails. This unit test can be safely rewritten to use a different exception type.
> Fix failing AppVeyor build

- Source/ReturnsExtensions.cs
- UnitTests/ReturnsExtensionsFixture.cs
> Add `ThrowsAsync` overload for non-generic `Task`

- Source/Mock.Generic.cs
Default mock object names are built from the type name and a hex  number. Instead of building that number from the first 4 digits of a GUID &mdash; a whole GUID is in practice unique, but the same does not hold true for only 4 of its digits &mdash;, create 8 unique (but non-random) hex digits in the simplest possible way: using a thread-safe ever-increasing counter.
It is still possible that the same number is used more than once, but this is now far less likely to happen in real-world scenarios: it would require the generation of more than 2<sup>32</sup> mock objects.
This fixes #348.
> Ensure default mock names are (more) unique

- Source/EmptyDefaultValueProvider.cs
- UnitTests/Regressions/IssueReportsFixture.cs
This commits extends `EmptyDefaultValueProvider` so it can generate default values for multi-dimensional arrays. Like with vectors, the default values for those consist of arrays with the proper rank and all-zero upper and lower bounds.
This fixes #311.
> Default values for multidimensional arrays

- Source/Interceptor.cs
- UnitTests/Regressions/IssueReportsFixture.cs
This PR is a cleaned-up version of #134. It fixes the buggy `Equals` and `GetHashCode` implementations in `Interceptor.ExpressionKey`. 
This closes #135, and closes #328.
> Fix equality check bug in ExpressionKey

- Source/It.cs
This fixes #269:
Testing a COM object's type using `IsAssignableFrom` can report false negatives because .NET might only see the generic RCW type `__ComObject` instead of the actual COM interface type. The `is` operator on the other hand appears to be performing `QueryInterface` for COM objects to get the right result.
This commit introduces an additional branch in `It.IsAny<>` that runs an `is`-based check for COM objects, and the as-is reflection-based check for everything else. The added logic takes effect only in builds targeting the full .NET Framework, since COM is not available on all .NET Core platforms.
I have successfully verified the new behaviour against a COM object, but am reluctant to add any permanent test code involving COM to Moq. That would tie the unit test project to …
> Make `It.IsAny`, `It.IsNotNull` work for COM types

- Source/Extensions.cs
- Source/Mock.cs
- Source/SerializableTypesValueProvider.cs
- UnitTests/Regressions/IssueReportsFixture.cs
This fixes #340.
Moq tries to work around DynamicProxy's refusal to proxy types that implement `ISerializable` improperly. It does so by defaulting to `EmptyDefaultValueProvider` for such types (which will never try to mock them, but simply returns `null` instead).
Moq's logic to detect bad `ISerializable` implementations however is currently faulty itself: It checks for the presence of a deserialization constructor and/or a virtual `GetObjectData` method without first checking whether the type in question implements `ISerializable`.
This issue gets fixed here. All necessary logic is moved to `SerializableTypesValueProvider` where it belongs. Additionally, tests are added that document why that class was added to Moq in the first place.
> Ensure incorrect implementations of ISerializable are caught properly

- Source/InterceptorStrategies.cs
- Source/MemberInfoExtensions.cs
- UnitTests/Regressions/IssueReportsFixture.cs
Up until now, if Moq encounters a method named `add_X` or `remove_X` it will assume that it's found an specialname event accessor method without performing any further checks.
This commits adds some trivial type checks and null reference checks to improve that logic somewhat. I hesitate to make this too perfect since that just might break things for F# or COM (see commit 44070a9).
This partially fixes #82.
> Make event accessor recognition logic more correct

- Moq.nuspec
- Source/Moq.NetCore.csproj
This is an amendment to 77db8c88fd8f1b075ddbed0b5baec93fa67a18f3 and e67faa9fddc85037e91e96c36f96ba7000e77dfd, which updated `System.*` package references to versions 4.3.0 and Castle.Core to version 4.1.0 but forgot to adjust the version numbers in `Moq.nuspec`.
It seems that `Moq.nuspec` is currently referencing many more packages than it needs to (most are added indirectly via `NETStandard.Library`). Remove superfluous references.
> Fix `Moq.nuspec` and package references

- Source/Mock.Generic.cs
- UnitTests/Regressions/IssueReportsFixture.cs
Commit 162a543 introduced a bug by handing over too many interfaces to Castle's `ProxyGenerator.CreateClassProxy` method. The intention behind that commit apparently was to enable `mock.As<TInterface>` even after `mock.Object` has already been called; something that wouldn't have been valid usage previously.
That change unfortunately also caused mocked classes' methods that implement an interface method to no longer be mocked correctly.
This commit fixes this problem by ensuring that the "internally implemented" interfaces are not explicitly passed to `.CreateClassProxy` (like it used to be done previously).
This fixes #156, #157, #175, and #331.
> Fix "unmockable interface methods" bug introduced by 162a543

- Source/Extensions.cs
- Source/Mock.cs
- UnitTests/Regressions/IssueReportsFixture.cs
PR #137 (commit 97a0f14) fixed a regression by changing the behavior of `mock.SetupAllProperties` so that read-only properties could be mocked, too. At the same time, it broke the frequent use case where a read-only property in a base interface is redeclared as a read-write property in a derived interface. Those redeclared properties would no longer be mocked correctly.
This commit reenables that scenario simply by changing the order in which properties are set up: properties in base interfaces (i.e. those furthest down the ancestor line) get set up before properties in more derived interfaces (i.e. those closer to the mocked type).
This fixes #162, #239, and #275.
> Fix mocking of redeclared interface methods

- Source/ExpressionStringBuilder.cs
- Source/Extensions.cs
- UnitTests/VerifyFixture.cs
This fixes #321.
Two inconsistencies have been reported in how arrays and arrays containing null references are reported in the "expected invocation" and "performed invocations" part of a `MockException` message:
1. In "expected invocation", arrays are completely omitted in the message.
2. In "performed invocations", null references are omitted in an array value dump.
This commit fixes both issues, and additionally ensures that in case of non-terminating or long sequences, only the first 10 elements are printed and the rest gets abbreviated as `", ..."`.
> Fix formatting inconsistencies for array values in MockException.Message

- Source/Mock.cs
- UnitTests/Regressions/IssueReportsFixture.cs
PR #381 (specifically, commit 0e3eaf3) broke the ability of mocking a non-virtual method if it is set up and called via an interface (`mock.As<TInterface>()`). This commit restores that feature.
This should fix #383.
> Fix mocking of non-virtual methods via interface

- Source/It.cs
- UnitTests/MatchersFixture.cs
Currently, matching `null` against any `It.IsRegex` placeholder will result in an `ArgumentNullException` being thrown by the framework. This is unintuitive.
This changes Moq behavior so that `null` will simply never match any `It.IsRegex`.
This fixes #266.
> Ensure that `null` never matches `It.IsRegex`

- Source/Properties/AssemblyInfo.cs
This is to remove the following build warning when used in a UWP app.
Moq.dll : warning MSB3817: The assembly "...nuget\packages\Moq\4.7.63\lib\netstandard1.3\Moq.dll" does not have a NeutralResourcesLanguageAttribute on it. To be used in an app package, portable libraries must define a NeutralResourcesLanguageAttribute on their main assembly (ie, the one containing code, not a satellite assembly).
> Add NeutralResourcesLanguage to Assembly info for portable library use

- Source/Interceptor.cs
Several methods in `Interceptor` currently read and modify a private dictionary without any synchronization or locking, which means that if someone tries to perform several setups concurrently on the same mock, they might run into a some multithreading-related exception every now and then.
Performing concurrent setups on the same mock is probably not a very frequent use case, but  it can't hurt to make Moq more thread-safe.
This should take care of #326.
> Make `Interceptor` more thread-safe

- Source/InterceptorStrategies.cs
- UnitTests/Regressions/IssueReportsFixture.cs
Moq does not currently mock an abstract event defined in a class correctly when a mock's `CallBase` is set to true. It will try to invoke the base event accessors (which are defined `abstract` in this case), which leads to DynamicProxy triggering a `NotImplementedException`.
This PR corrects that bug by suppressing the call to `InvokeBase` for event attach / detach accessors when the base accessor methods are abstract. (Up until now, such a check was in place only for events defined in interfaces.)
This fixes #296.
> Make abstract events defined in classes work even when `CallBase` is true

- Source/Linq/MockSetupsBuilder.cs
- UnitTests/Regressions/IssueReportsFixture.cs
> Allow setting up null return values using `Mock.Of`

- Source/Extensions.cs
- Source/MemberInfoWithTarget.cs
- Source/MethodCall.cs
- Source/Mock.Generic.cs
- Source/Moq.csproj
- UnitTests/MockedEventsFixture.cs
- UnitTests/Regressions/IssueReportsFixture.cs
> Allow `Mock<T>.Raise` to raise events on child mocks

- Source/Extensions.cs
- Source/Mock.cs
- Source/Moq.NetCore.csproj
- Source/Obsolete/Mock.Legacy.cs
- Source/Properties/Resources.Designer.cs
- Source/Properties/Resources.resx
> Improve Setup / Verify exception messages for static members and extension methods

- Source/ExpressionStringBuilder.cs
- Source/Extensions.cs
- Source/Linq/MockSetupsBuilder.cs
- Source/Linq/Mocks.cs
- Source/MethodCall.cs
- Source/Mock.cs
- Source/Properties/Resources.Designer.cs
- Source/Properties/Resources.resx
- Source/Protected/ProtectedMock.cs
- Source/ReturnsExtensions.cs
- UnitTests/Regressions/IssueReportsFixture.cs
- UnitTests/VerifyFixture.cs
> Move hardcoded message strings to `Resources.resx`

- Source/FluentMockContext.cs
- UnitTests/MockDefaultValueProviderFixture.cs
Ok, trying again. I hope that this PR is now OK - there are only 2 files changed.
The fix for #409 is to revert the order of the items of the invocations list in he FluentMockContext before disposing the items. The new test runs into a situation, that there are at least 2 MockInvocations created on the mock which is constructed with DefaultValue.Empty. The first one remembers the original DefalutValue (Empty) and sets it to Mock. The second one remembers the current value of DefaultValue (Mock) and sets it to the Mock, too. Now, if the MockInvocations are disposed in the same order as they were created, the first MockInvocation will set the DefaultValue of the mock back to the value it remembered - Empty. Then the second MockInvocation is disposed and sets the DefaultValue to the Mock, as …
> Fix for the #409

- Source/ExpressionStringBuilder.cs
- Source/Extensions.cs
- Source/Matchers/ConstantMatcher.cs
- UnitTests/Regressions/IssueReportsFixture.cs
> IEnumerable mocks shouldn't cause NullReferenceException

- Source/InterceptorStrategies.cs
- UnitTests/Regressions/IssueReportsFixture.cs
If you're setting up methods in a type hierarchy (e.g. `Base.Method` and `Derived.Method`), the setup order currently matters, even though two different methods are set up.
This commits is a first step in making Moq associate the "right" setup with a proxy method invocation. This will make sure that if there are several setups that potentially match an invocation, it will attempt to pick the one for the exact same method.
This is only a start, but probably still not good enough in all situations (for example, for overridden methods, the distance of the inheritance relationship is not taken into account).
This should fix #131.
/cc @dcastro, @pjquirk
> Improve method match accuracy in `ExtractProxyCall`

- Source/IProxyCall.cs
- Source/MethodCall.cs
- Source/Mock.cs
- UnitTests/Regressions/IssueReportsFixture.cs
This is a fix for #211.
When `mock.Verify` fails, it lists the mock's setups in the exception message. However, it reports actual invocation counts as the number of expected calls set up, which is misleading at best and incorrect at worst.
Moq currently allows only two kinds of expected call count setups (both of which have been obsoleted): `.AtMostOnce()` and `.AtMost(n)`. The current logic for formatting a setup is moved to `MethodCall` (the class representing a setup) where it rightly belongs, and where the expected call count limit is accessible.
This change will also make it easier to introduce the ability to specify any `Times` on a setup, if that's what gets decided in #373.
> Fix misreported setup `Times` in `Verify` messages

- UnitTests/Regressions/IssueReportsFixture.cs
Using a mocked IEnumerable in the setup of a method call shouldn't cause
any exceptions.
> Add regression test for issue #421

- CHANGELOG.md
- Source/Mock.cs
- UnitTests/Regressions/IssueReportsFixture.cs
`mock.SetupAllProperties` recursively sets up all properties in a whole object graph, and because of this contains some logic that tries to prevent infinite loops due to recursive types. That logic works by putting the types of all encountered / "traversed" / mocked properties onto a stack, but currently forgets to ever pop them off again.
This fixes #438.
> Make `SetupAllProperties` work correctly for same-typed sibling properties

- CHANGELOG.md
- Source/Moq.csproj
- build.proj
Prior to Visual Studio 2017 Update 3, the Roslyn compilers only supported SourceLink for the new portable PDB format. With Update 3, SourceLink is also supported with the classic Windows PDB format.  This PR reverts back from portable PDBs to classic PDBs because some existing .NET tooling (among them TFS, apparently) simply cannot yet deal with portable PDBs correctly, causing some people's build processes to fail.
This is intended to fix #428.
> Switch back from portable PDBs to classic PDBs

- CHANGELOG.md
- Source/InterceptorStrategies.cs
- Source/MethodCallReturn.cs
- UnitTests/Regressions/IssueReportsFixture.cs
> Make strict mocks recognize that `.CallBase()` can set up a return value, too

- CHANGELOG.md
- Moq.VisualBasicTests/project.json
- Moq.nuspec
- Source/Moq.csproj
- UnitTests/Moq.Tests.csproj
Due to the new versioning scheme adopted by Castle.Core 4.2.0, problems such as #418 should be less likely to happen in the future.
This closes #425.
> Update Castle.Core to version 4.2.0

- CHANGELOG.md
- Source/AsInterface.cs
- UnitTests/AsInterfaceFixture.cs
- UnitTests/Regressions/IssueReportsFixture.cs
> Let `.As<T>` mocks generate same proxy as the uncast mock

- appveyor.yml
Working on a separate `develop` branch rather than directly on `master` has had one big benefit, namely that not every PR merge or other commit immediately triggered a new NuGet package release. We could prepare the next release on `develop`, and then merge into `master` to publish. However, maintaining two branches introduced its own problems, e.g.:
* It is hard to predict the version number to be put into `CHANGELOG.md`, since `master` has additional merge commits that `develop` doesn't have, so [GitInfo](https://github.com/kzu/GitInfo) arrives at a different (later) version number on `master`.
* The `master` branch is still set up as default, so PRs are often made against the wrong branch.
This PR is a first step towards a different publish procedure: If all goes as planned, we can …
> Push to NuGet on tag, not on commit to master branch

- CHANGELOG.md
- Source/MethodCall.cs
- UnitTests/OccurrenceFixture.cs
> Update invocation count correctly, even when setup throws exception

- CHANGELOG.md
- Moq.VisualBasicTests/project.json
- Moq.nuspec
- Source/Moq.csproj
- UnitTests/Moq.Tests.csproj
- UnitTests/Regressions/IssueReportsFixture.cs
This new version of Castle DynamicProxy is a "hotfix" release for a regression; see castleproject/Core#309.
This closes #469 and #470.
> Update Castle.Core to version 4.2.1

- CHANGELOG.md
- Moq.Tests/VerifyFixture.cs
- Source/InterceptorStrategies.cs
This resolves #487. Should have been fixed back with #376.
>  Record calls to methods with event accessor-like names

- CHANGELOG.md
- Moq.Tests/ExpressionExtensionsFixture.cs
- Moq.Tests/PropertiesFixture.cs
- Source/ExpressionExtensions.cs
This fixes #496.
Given the two types `FooBase` and `Foo` in that issue and the following expression tree:
```csharp
Expression<Func<Foo, object>> expression = foo => foo.Property;
```
If one inspects the `PropertyInfo` that the compiler puts into `expression` for `foo.Property`, it'll be the `PropertyInfo` representing `FooBase.Property` instead of `Foo.Property`. (See also the [this Stack Overflow question, "ReflectedType from MemberExpression"](https://stackoverflow.com/questions/23105567/reflectedtype-from-memberexpression).)
This PR adds code to Moq's `expression.ToPropertyInfo()` extension method to counteract this peculiar C# compiler behaviour.
> Improve `Setup` recognition logic for sealed methods

- CHANGELOG.md
- Moq.Tests/PropertiesFixture.cs
- Source/Mock.cs
> Let `SetupAllProperties` skip inaccessible methods

- CHANGELOG.md
- Moq.Tests/ProtectedAsMockFixture.cs
- Source/Properties/Resources.Designer.cs
- Source/Properties/Resources.resx
- Source/Protected/IProtectedAsMock.cs
- Source/Protected/IProtectedMock.cs
- Source/Protected/ProtectedAsMock.cs
- Source/Protected/ProtectedMock.cs
This proposes a new feature that aims to offer more complete support for setting up and verifying protected members (including the ability to set up protected generic methods, and protected methods with by-ref parameters).
It closes #223 and #249 if merged.
The current `Setup` and `Verify` methods accessible via `mock.Protected()` admittedly offer a handy way to get at protected members, but with the following downsides:
* They are by necessity completely "untyped". As such, they do not fit well into Moq's generally strongly-typed API.
* They are not easy to extend with support for generic methods, or methods with by-ref parameters.
The new feature proposed here adds a new method, `mock.Protected().As<TDuck>()`, which offers `Setup` and `Verify` methods by which protected members can be …
> Introduce `.Protected().As<TDuck>()` to perform duck-typed setup and verification of protected members

- CHANGELOG.md
- Moq.Tests/ProtectedAsMockFixture.cs
- Source/Protected/ProtectedAsMock.cs
> `Protected().As<T>()`: Fix generic method support

- CHANGELOG.md
- Moq.Tests/ReturnsExtensionsFixture.cs
- Moq.nuspec
- Source/Moq.csproj
- Source/ReturnsExtensions.Generated.cs
- Source/ReturnsExtensions.cs
- Source/ReturnsExtensions.tt
Addresses #437  
- Reference NuGet System.Threading.Tasks.Extensions
- Add extension methods to ReturnsExtensions.cs/.tt
- Add unit tests to ReturnsExtensionsFixture.cs
Tests pass on NetCoreApp2.0 and Net46 TFMs.
> Add ValueTask extensions

- Source/Mock.Generic.cs
- Source/Mock.cs
- Source/PexProtector.cs
`PexProtector.Invoke` annoyingly breaks step-debugging through affected parts of Moq's source code. This commit solves this (and, besides, reduces object allocations caused by the lambda's variable capturing).
Hopefully, at a later point, we can get rid of `PexProtector` entirely. (Is anyone actually using Pex / Smart Unit Tests / IntelliTest these days?)
> Get `PexProtector` out of the debugger's way

- CHANGELOG.md
- Moq.Tests/Moq.Tests.csproj
- Moq.Tests/Regressions/IssueReportsFixture.cs
- Source/ExpressionStringBuilder.cs
- Source/Extensions.cs
This resolves both #464 (for which a regression test is added) and #478.
> Prevent Moq from relying on a mock's implementation of IEnumerable<T>

- CHANGELOG.md
- Moq.Tests/AsInterfaceFixture.cs
- Moq.Tests/MockDefaultValueProviderFixture.cs
- Moq.Tests/MockFixture.cs
- Moq.Tests/RecursiveMocksFixture.cs
- Moq.Tests/Regressions/IssueReportsFixture.cs
- Moq.Tests/VerifyFixture.cs
- Source/Diagnostics/Errors/IError.cs
- Source/Diagnostics/Errors/UnmatchedSetups.cs
- Source/Diagnostics/Errors/UnmatchedSetupsAggregated.cs
- Source/Interceptor.cs
- Source/Mock.cs
- Source/MockException.cs
- Source/Obsolete/MockFactory.cs
> Remove leaked `MockVerificationException` and catch-throw-recatch cycle during verification

- CHANGELOG.md
- Source/AsInterface.cs
- Source/MethodCall.cs
- Source/Mock.cs
- Source/Obsolete/MockFactory.cs
- Source/Switches.cs
- UnitTests/MockDefaultValueProviderFixture.cs
- UnitTests/MockFixture.cs
- UnitTests/MockRepositoryFixture.cs
- UnitTests/VerifyFixture.cs
Up until now, Moq has been collecting source file information for each setup created. This came at a slight performance penalty. There is currently a regression in the .NET Framework which means this penalty becomes gigantic (more expensive than proxy creation!).
This commit turns source file information collection into an opt-in feature. Towards that end, a `Switches` property is added to `Mock` and `MockRepository` which allows users to opt in or out of certain features. Source file info collection is controlled via the switch `Switches.CollectDiagnosticFileInfoForSetups`.
> Turn collection of source file information per setup into an opt-in feature

- CHANGELOG.md
- Moq.Tests/CustomMatcherFixture.cs
- Source/ExpressionExtensions.cs
> Ensure custom matcher properties print correctly in verification error messages

- CHANGELOG.md
- Moq.Tests/ReturnsValidationFixture.cs
- Source/MethodCall.cs
- Source/MethodCallReturn.cs
- Source/Properties/Resources.Designer.cs
- Source/Properties/Resources.resx
This PR adds minimal validation logic for delegates passed to `Returns`:
* Return type must be assignment compatible
* Parameter count must match
While it would be desirable from a technical standpoint, parameter types do not get checked for assignment compatibility due to two possibly widespread practices:
* Callback uses a by-value callback parameter while method being set up has a by-ref-parameter:
```csharp
TArg expectedX = ...;
mock.Setup(m => m.Method(ref expectedX).Returns<TArg>(actualX => ...);
```
* Callback uses a subtype and setup uses a matcher to ensure runtime value conversion will always succeed:
```csharp
mock.Setup(m => m.MethodWithObjectParam(It.IsAny<int>()).Returns<int>(i => ...);
mock.Setup(m => m.MethodWithObjectParam(It.IsAny<string>()).Returns<string>(str => ...); …
```
> Validate delegates passed to `Returns` more strictly

- Source/EmptyDefaultValueProvider.cs
This is a lot more efficient (I observed speed-ups of simple mock method invocations by 67%) and makes it possible to easily add handling of additional types that are currently ignored (such as `List<T>`, `IReadOnlyList<T>`, etc.).
> Rewrite `EmptyDefaultValueProvider` to use dictionary lookup for special type handling

- CHANGELOG.md
- Moq.Tests/Regressions/IssueReportsFixture.cs
- Source/Linq/MockSetupsBuilder.cs
> Prevent infinite loop when invoking delegate in `Mock.Of` setup expression

- CHANGELOG.md
- Moq.Tests/EmptyDefaultValueProviderFixture.cs
- Source/EmptyDefaultValueProvider.cs
#506 added support for `ValueTask<TResult>` to the `ReturnsAsync` method group. If Moq has support for `ValueTask<TResult>` in one place, it should consistently support that type everywhere.
This PR therefore adds special handling of that type for `DefaultValue.Empty`: Moq will produce a completed `ValueTask<TResult>` containing an empty `TResult` value for type members having a return type of `ValueTask<TResult>`.
> Add support for `ValueTask<TResult>` to `DefaultValue.Empty`

- CHANGELOG.md
- Moq.Tests/MockDefaultValueProviderFixture.cs
- Source/InterceptorStrategies.cs
- Source/Linq/Mocks.cs
- Source/Mock.cs
- Source/MockDefaultValueProvider.cs
- Source/MockWithWrappedMockObject.cs
This PR enables the following scenario (shown for `Task<T>`, but same goes for `ValueTask<T>`):
```csharp
var mock = new Mock<IFoo>() { DefaultValue = DefaultValue.Mock };
var property = (await mock.Object.GetBarAsync()).Property;
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// With DefaultValue.Mock, Task<T> no longer returns tasks
// that resolve to default(T), but to a mocked T, so these are
// now awaitable straight away.
public interface IFoo
{
Task<IBar> GetBarAsync();
}
public interface  IBar
{
object Property { get; }
}
```
This closes #171.
> Allow `DefaultValue.Mock` to mock `Task<TMockable>` and `ValueTask<TMockable>`

- Moq.Tests/EmptyDefaultValueProviderFixture.cs
- Moq.Tests/MockDefaultValueProviderFixture.cs
- Source/DefaultValueProvider.cs
- Source/EmptyDefaultValueProvider.cs
- Source/Linq/Mocks.cs
- Source/Mock.Generic.cs
- Source/Mock.cs
- Source/MockDefaultValueProvider.cs
- Source/Obsolete/MockFactory.cs
- Source/SerializableTypesValueProvider.cs
so that it mirrors `DefaultValue` more closely:
```csharp
new Mock<T> { DefaultValue         = DefaultValue        .Mock }
new Mock<T> { DefaultValueProvider = DefaultValueProvider.Mock }
```
This also creates a single access point for further standard default value providers in the future.
> Add `Empty`, `Mock` properties to `DefaultValueProvider`

- CHANGELOG.md
- Moq.Tests/LookupOrFallbackDefaultValueProviderFixture.cs
- Source/EmptyDefaultValueProvider.cs
- Source/LookupOrFallbackDefaultValueProvider.cs
- Source/MockDefaultValueProvider.cs
This adds a new base class `LookupOrFallbackDefaultValueProvider`, which builds on top of `DefaultValueProvider`, to Moq's public API.
* This type becomes the new base class for both `EmptyDefaultValueProvider` and `MockDefaultValueProvider`.
* It has inbuilt support for task types `Task`, `Task<TResult>`, and `ValueTask<TResult>`.
* It also provides enough customizability for folks to easily create their own default value providers that work like the empty default value provider. Here's an example of a provider that will produce empty collections for `IReadOnlyList<T>`:
```csharp
sealed class MyEmptyDefaultValueProvider : LookupOrFallbackDefaultValueProvider
{
public MyEmptyDefaultValueProvider()
{
base.Register(typeof(IReadOnlyList<>), CreateReadOnlyListOf);
}
private static …
```
> New `LookupOrFallbackDefaultValueProvider` base class for custom default value providers

- CHANGELOG.md
- Moq.Tests/MatchersFixture.cs
- Source/It.cs
- Source/Matchers/AnyMatcher.cs
- Source/MethodCall.cs
- Source/Protected/ItExpr.cs
- Source/Protected/ProtectedMock.cs
This PR adds `It.Ref<T>.IsAny` which is to `ref` parameters what `It.IsAny<T>()` is to regular by-value parameters:
```csharp
interface IFoo
{
void Do(ref int n);
}
var mock = new Mock<IFoo>();
mock.Setup(m => m.Do(ref It.Ref<int>.IsAny));
```
This resolves #479.
> Match any values for `ref` parameters using `It.Ref<TValue>.IsAny` / `ItExpr.Ref<TValue>.IsAny`

- Source/AsInterface.cs
- Source/Mock.Generic.cs
- Source/Mock.cs
Mock state and initialization is currently split across both `Mock` and `Mock<T>`. This is not ideal for at least three reasons:
1. It is difficult to get an idea how much state a mock object really carries.
2. It can be hard to understand control flow (e. g. with mock object initialization), which might bounce back and forth between methods defined in both `Mock` and `Mock<T>`.
3. It's relatively easy to introduce `As<TInterface>`-related bugs by directly referencing backing fields instead of their corresponding properties. `As<TInterface>` mocks do not use their own backing fields (which remain completely uninitialized), but instead delegate all properties to the "owner" mock's. Therefore, for `As<TInterface>` mocks to work correctly, code should always reference the properties, and …
> Move state (fields) from `Mock` into `Mock<T>`

- Source/AsInterface.cs
- Source/Interception/InterceptionAspects.cs
- Source/Mock.Generic.cs
- Source/Mock.cs
`ImplementedInterfaces` together with `InternallyImplementedInterfaceCount` contains three logically semi-separate sets of interface types:
1. interface types inherited from the mocked type
2. `IMocked<T>`
3. additional interface types requested through `As<TInterface>()`
Combining these three into a single collection results in some rather convoluted code.
This commit pries these three things apart: (1) is turned into a `InheritedInterfaces` property, which is implemented using a static backing field, (2) is directly referenced where required, and (3) is turned into a `AdditionalInterfaces` property.
This results in simpler code and reduced memory consumption.
> Refactor `ImplementedInterfaces` contraption

- Moq.Tests/CustomDefaultValueProviderFixture.cs
- Source/FluentMockContext.cs
Bug fix related to the introduction of `DefaultValueProvider`.
> Restore default value provider correctly in `FluentMockContext`

- Moq.Tests/VerifyFixture.cs
- Source/Linq/Mock.cs
- Source/Linq/Mocks.cs
This PR ensures that mocks created with `Mock.Of<T>` initially have no recorded invocations.
Due to the way `Mock.Of<T>` is currently implemented, mocks created using this method might already have recorded invocations. This never really mattered up until now, where it can interfere with `VerifyNoOtherCalls`.
This solves one of two issues with the initial `VerifyNoOtherCalls` implementation, as tracked in  https://github.com/moq/moq4/issues/527#issuecomment-348697314.
> `VerifyNoOtherCalls`: Fix bugs with `Mock.Of<T>`

- Moq.Tests/VerifyFixture.cs
- Source/InvocationCollection.cs
- Source/Mock.cs
This PR ensures that `VerifyNoOtherCalls` gets along more or less nicely with multi-dot ("recursive") verification expressions.
Recursive expressions are generally a pain point in Moq, and the way they are implemented lead to all sorts of trouble. Quite a few of the currently remaining bug reports are directly related to that particular aspect of Moq. I'm expecting that despite the improvements in this PR, people might sooner or later discover that `VerifyNoOtherCalls` acts a little weird in circumstances where multi-dot expressions and automatically mocked sub-objects are involved.
(Fixing these multi-dot expression troubles is semi-planned for Moq 4.9 or 4.10.)
This solves the second of two issues with the initial `VerifyNoOtherCalls` implementation, as tracked in …
> `VerifyNoOtherCalls`: fix bugs with multi-dot expressions

- Source/MethodCall.cs
- Source/Mock.cs
- Source/PropertyGetterMethodCall.cs
- Source/PropertySetterMethodCall.cs
Excessive reflection in `SetupAllProperties` contributes to `Mock.Of<T>`'s bad performance (#547).
This PR reduces use of reflection in this method by adding instances of specialized `MethodCall` types directly to `mock.Setups`, instead of installing setups by making calls to `mock.SetupProperty(m => m.Property, initialValue)` or `mock.SetupGet(m => m.Property).Returns(value)` through reflection.
> Reduce use of reflection in `SetupAllProperties`

- CHANGELOG.md
- Moq.Tests/Regressions/FluentMockIssues.cs
- Moq.Tests/Regressions/IssueReportsFixture.cs
- Source/Mock.cs
- Source/PexProtector.cs
Let `SetupAllProperties` defer initialization of set up properties to the point when they are queried for the very first time. Doing this has two advantages:
1. There is no more immediate difference in execution speed between `DefaultValue.Empty` and `DefaultValue.Mock`. (Up until now, `SetupAllProperties` could be orders of magnitude slower when used with the latter default value mode.)
2. Type recursion / loops in the object graph are no longer an issue (hence the changes to the unit tests). We no longer need to keep track of already mocked types, so we can get rid of `GetInitialValue` and call `GetDefaultValue` directly.
> `SetupAllProperties`: Defer property initialization

- Source/ProxyFactories/CastleProxyFactory.cs
- Source/ProxyFactories/InterfaceProxy.cs
Creating proxies with DynamicProxy is the single most expensive kind of operation that Moq does. Commit 54e132b changed how proxies for interface types are generated so that `object` methods on interfaces could also be intercepted (and thus set up). Unfortunately, this change also made interface proxy generation twice as costly!
This commit restores the previous method for interface proxy creation, and at the same time adds an `InterfaceProxy` class to keep `object` methods interceptable.
This should bring Moq's performance back to, or very close to, what it used to be before version 4.5.16.
/cc #504
> Make interface proxy creation twice as fast

- Moq.Tests.VisualBasic/Moq.Tests.VisualBasic.vbproj
- Moq.Tests/Moq.Tests.csproj
Sadly, .NET Core tooling doesn't seem to be smart enough anymore to choose an appropriate .NET Core runtime host version itself when it is given `netcoreapp2.0` as the target platform. If we don't explicitly
tell it which precise host version to use, it'll flat out refuse to execute code (the xUnit tests, in our case).
Alternatively, I'm not smart enough to understand .NET Core. But I seem to remember that things used to just work not too long ago.
See https://github.com/dotnet/cli/issues/7901.
> Build script: Fix xUnit test run for .NET Core

- CHANGELOG.md
- Source/Properties/AssemblyInfo.cs
The rationale behind this is that we don't want changes in the patch version to result in a different strong name; patches should be in-place updates and shouldn't lead to version conflicts.
This will help reduce the need for assembly binding redirects.
For now, we only do 'major.minor.0.0' instead of 'major.0.0.0' (which would be even better).
For the next release, we'll have to increase the minor version by 1 to rule out strange-looking binding redirects like these:
4.0.0.0 - 4.7.145.0  ->  4.0.0.0
4.0.0.0 - 4.7.145.0  ->  4.7.0.0
In both cases, the following will probably look less suspicious:
4.0.0.0 - 4.7.145.0  ->  4.8.0.0
Moq 5 will be able to safely make the switch to 'major.0.0.0'.
This closes #424.
> Adopt assembly versioning scheme 'major.minor.0.0'

- CHANGELOG.md
- Moq.Tests/Regressions/IssueReportsFixture.cs
- Source/Interception/InterceptionAspects.cs
> Fix `CallBase` regression with explicitly implemented interface methods

- Moq.nuspec
- Source/Moq.csproj
Hopefully, this will take care of the better part of #566 and #567 and restore better compatibility of Moq with the full .NET Framework <4.7.1.
> Downgrade System.ValueTuple & System.Threading.Tasks.Extensions

- CHANGELOG.md
- Moq.Tests/ReturnsValidationFixture.cs
- Source/MethodCallReturn.cs
Add more parameters to test method as 0 and 1 parameters are special cases for parameterless and extension methods.
Add tests for extension methods with different number of parameters.
> Issue #572 Setup cannot invoke callback with different number of parameters in Moq 4.8.1

- CHANGELOG.md
- Moq.Tests/Regressions/IssueReportsFixture.cs
- Source/Interception/InterceptionAspects.cs
This fixes #582. (See commit messages for details.)
> Ignore CallBase for members of additional interfaces

- CHANGELOG.md
- Moq.nuspec
- Source/Moq.csproj
This resolves #578.
(This change also bears the potential to retrigger problems similar to #566, which is why I tested this against different target frameworks&mdash;from `net45` up to `net471` and both `netcoreapp1.0` and `netcoreapp2.0`. Visual Studio didn't report any assembly versioning conflicts, so I am reasonably confident that this is good to go.)
> Upgrade dependency on System.ValueTuple to version 4.4.0

- CHANGELOG.md
- Moq.Tests/SequenceExtensionsFixture.cs
- Source/Language/Flow/SetupSequencePhrase.cs
- Source/Language/ISetupSequentialResult.cs
- Source/SequenceMethodCall.cs
Added new method overloads:
```
public interface ISetupSequentialResult<TResult>
{
...
ISetupSequentialResult<TResult> Returns(Delegate valueFunction);
ISetupSequentialResult<TResult> Returns(Func<TResult> valueExpression);
...
}
```
They are needed to resolve #592
> Added `ISetupSequentialResult<TResult>.Returns` method overload that support delegate for deferred results

- CHANGELOG.md
- Moq.Tests/Regressions/IssueReportsFixture.cs
- Source/ReturnsExtensions.cs
- Source/SequenceExtensions.cs
>  Fixed UnobservedTaskException after using ThrowsAsync. Fixed ReturnsAsync and ThrowsAsync with delay

- CHANGELOG.md
- Source/Linq/Mock.cs
- Source/Linq/Mocks.cs
https://github.com/moq/moq4/issues/547
PR not finished yet ...
> Replace Mock.Of code with 10x faster equivalent

- CHANGELOG.md
- Moq.Tests/Moq.Tests.csproj
- Moq.nuspec
- Source/Moq.csproj
> Update Castle.Core to version 4.3.0

- CHANGELOG.md
- Moq.Tests/Moq.Tests.csproj
- Moq.Tests/Regressions/IssueReportsFixture.cs
This adds a few tests, including those mentioned in https://github.com/castleproject/Core/issues/339#issue-304443306 and https://github.com/castleproject/Core/issues/339#issuecomment-372605885, to document the state of `in` parameter modifier support.
As it turns out, the previous update of Castle.Core to 4.3.0 makes `in` parameter modifiers work on .NET Core even though Moq doesn't specifically target .NET Standard 1.5 or above... it suffices that Castle.Core does that.
(.NET Standard 1.3 vs 1.5 is important because the latter includes the System.Reflection.Emit facilities required for mocking `in`; more specifically, the ability to emit custom modifiers.)
This closes #605.
> Verify that `in` parameter modifier is supported

- CHANGELOG.md
- Moq.Tests/VerifyFixture.cs
- Source/AsInterface.cs
- Source/IReadOnlyInvocation.cs
- Source/Interception/InterceptionAspects.cs
- Source/Invocation.cs
- Source/InvocationCollection.cs
- Source/Mock.Generic.cs
- Source/Mock.cs
- Source/MockExtensions.cs
Second take at exposing invocation information.
Invocation information exposed via `IReadOnlyInvocation` interface.
Mock invocations exposed via property `IReadOnlyList<IReadOnlyInvocation> Invocations` on `Mock` class.
> Expose invocations

- Moq.Tests/InvocationsFixture.cs
- Source/InvocationCollection.cs
Add tests for `Mock.Invocations` property.
Improved `InvocationCollection` to no longer allocate a copy of the collection on enumeration.
> Invocations collection improvements

- Moq.Tests/ExpressionExtensionsFixture.cs
- Moq.Tests/Matchers/AnyMatcherFixture.cs
- Source/ExpressionExtensions.cs
- Source/MethodCall.cs
- Source/MethodCallReturn.cs
- Source/Mock.cs
- Source/PropertyGetterMethodCall.cs
- Source/PropertySetterMethodCall.cs
- Source/SequenceMethodCall.cs
- Source/SetterMethodCall.cs
This is the first out of several refactorings that attempt to get rid (as much as possible) of chained expression transforms such as `.PartialMatcherAwareEval().ToLambda()` which are found all over the codebase. They are problematic because it's not immediately clear *when* these transforms are needed, and *which* of them are needed for what reasons.
`.ToLambda()` is a mix-up of two separate concerns:
1. Perform a downcast from `Expression` to `LambdaExpression`
2. Strip a type-cast (if present) from the lambda's body
As it turns out, (1) becomes superfluous if we simply re-declare certain members as `LambdaExpression` instead of `Expression`. Incidentally, this makes visible the heretofore implicit assumption that `MethodCall.SetupExpression` is expected to be a lambda expression. …
> Replace `.ToLambda()` conversions with static typing

- Moq.Tests/ExpressionExtensionsFixture.cs
- Source/ExpressionExtensions.cs
- Source/MethodCall.cs
- Source/Mock.cs
There's a helper method `ExpressionExtensions.StripConversion(this LambdaExpression)` that doesn't appear to have any effect whatsoever. It can be turned into an identity function and none of the unit tests break.
A closer inspection reveals the following:
* The comment it contains about the `LambdaExpression` ctor introducing a cast no longer appears to hold true today. Also, the reference to `ProtectedMockExtensions` is rather vague. It looks a lot like things have changed so much since this code was added that it just no longer makes any sense.
* The method is used *only* in diagnostic scenarios (i.e. when an exception is about to be thrown). It is strange that automatically added conversions would only have to be removed when we're about to error already, but not in normal operation. …
> Remove superfluous `.StripConversion` helper method

- Moq.Tests/ExtensionsFixture.cs
- Moq.Tests/InvocationsFixture.cs
- Source/IInvocation.cs
- Source/IInvocationList.cs
- Source/Invocation.cs
- Source/InvocationCollection.cs
- Source/Linq/Mock.cs
- Source/Mock.cs
- Source/MockExtensions.cs
- Source/Obsolete/MockExtensions.cs
- Source/ProxyFactories/CastleProxyFactory.cs
Rename `IReadOnlyInvocation` to `IInvocation` and introduce a new type `IInvocationList` instead of using `IReadOnlyList<>`. The rationale behind this is that we may want to publish methods in the future that are not read-only; naming interfaces as "read-only" would essentially block us from doing so.
Deprecate `mock.ResetCalls()` in favor of `mock.Invocations.Clear()`, which is more in line with Moq 5's API.
> `IInvocation` and `IInvocationList`

- CHANGELOG.md
- Source/StringBuilderExtensions.cs
`Single.ToString()` and `Double.ToString()` use the `"G"` format specifier by default, which does not include all significant digits in the produced output.
Change the diagnostic formatting code so that it uses a round tripping representation for floating point numbers (like e.g. the Visual Studio debugger does, too). Instead of the somewhat unreliable `"R"` specifier, use `"G9"` (for singles) and `"G17"` (for doubles) as documented on [Standard Numeric Format Strings: The General ("G") Format Specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#the-general-g-format-specifier).
This closes #636.
> Round-trip floats in diagnostic messages

- Moq.nuspec
- Source/Moq.csproj
Moq doesn't just require the `System.Reflection.Emit` package because `Castle.Core` requires it; Moq also uses the functionality provided by that package directly when mocking delegate types. Therefore, add it
as an explicit dependency.
> Add missing dependency to `System.Reflection.Emit`

- Source/MethodCall.cs
According to [that](https://www.codeproject.com/Articles/990/Understanding-Classic-COM-Interoperability-With-NE) rules ('Mapping method parameter keywords in C# to IDL's Directional attributes' section) and [MSDN description](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/77e6taeh(v=vs.90)) about Directional Attributes, the c# 'out' method parameter keyword maps to only [out] directional attribute. But in the current implementation if the parameter has [in,out] directional attributes the Moq framework is gonna take it as 'out' parameter, which is wrong, because according to the rules in the article and msdn reference i posted above it gotta take it as 'ref' parameter, not the out. This situation may ocuur for example when you try to mock the COM …
> The condition determining whether a parameter is 'out' parameter is changed

- CHANGELOG.md
- src/Moq/CaptureMatch.cs
- src/Moq/DefaultExpressionCompiler.cs
- src/Moq/Evaluator.cs
- src/Moq/ExpressionCompiler.cs
- src/Moq/ExpressionExtensions.cs
- src/Moq/It.cs
- src/Moq/Linq/MockQuery.cs
- src/Moq/MatcherFactory.cs
- src/Moq/Mock.cs
- src/Moq/Moq.csproj
- src/Moq/Protected/ProtectedMock.cs
As contemplated in https://github.com/moq/moq4/issues/504#issuecomment-406728206.
This would enable users to configure Moq to use their own LINQ expression tree compilation strategies, such as:
* add a caching layer, as originally proposed in https://github.com/moq/moq4/issues/188#issuecomment-368027246;
* use a different (possibly faster) library for compilation, as suggested in https://github.com/moq/moq4/issues/504#issuecomment-406714210.
It would seem like a nice feature to merge, since it enables some new options and is trivial to implement.
> Add extensibility point for LINQ expression tree compilation

- CHANGELOG.md
- src/Moq/MethodCallReturn.cs
- tests/Moq.Tests/CallbackDelegateValidationFixture.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
- tests/Moq.Tests/ReturnsDelegateValidationFixture.cs
> Prevent false parameter count mismatch when using compiled methods with `Returns`

- src/Moq/MatcherFactory.cs
- src/Moq/Matchers/ParamArrayMatcher.cs
- src/Moq/MethodCall.cs
- tests/Moq.Tests/Matchers/AnyMatcherFixture.cs
Logic for creating argument matchers from argument expressions has so far been spread over `MatcherFactory` and one `MethodCall` ctor. This refactoring places all of it where it belongs: into `MatcherFactory`.
This comes at the small additional cost of iterating over arguments a second time to identify `out` parameters and gather their values, but the added code clarity and clearer responsibilities seem worth it.
> Move matcher selection logic into `MatcherFactory`

- src/Moq/InvocationShape.cs
- src/Moq/MethodCall.cs
- src/Moq/Mock.cs
- src/Moq/MockException.cs
- src/Moq/Obsolete/Mock.Legacy.cs
This refactoring moves all logic from `MethodCall` that is related to invocation matching into a dedicated new type, `InvocationShape`. This is useful mainly because of two reasons:
1. The invocation matching becomes more easily testable once it is better isolated.
2. Verification methods such as `mock.Verify(expression)` no longer need to instantiate a transient `MethodCall` (which at its heart really represents a setup) in order to match invocations. They will be able to use the much lighter-weight `InvocationShape` instead.
> Extract invocation matching logic into `InvocationShape`

- CHANGELOG.md
- src/Moq/Language/Flow/ICallBaseResult.cs
- src/Moq/Language/Flow/ICallbackResult.cs
- src/Moq/Language/Flow/NonVoidSetupPhrase.cs
- src/Moq/Language/Flow/SetupPhrase.cs
- src/Moq/Language/ICallBase.cs
- src/Moq/MethodCall.cs
- src/Moq/MethodCallReturn.cs
- tests/Moq.Tests/CallBaseFixture.cs
This closes #615.
Note that this adds a new minor inconsistency in the API: For non-void methods, it is possible to specify a `.Callback()` both before *and after* `.CallBase()`. The change proposed here only adds `.CallBase()` for void methods, but without the option of a subsequent call to `.Callback()`. It is left to a future PR to rectify this. (However, judging from [the original feature request on Google Code](https://code.google.com/archive/p/moq/issues/19) and the preceding discussion linked there, it seems unlikely that anyone would actually need this.)
> Add `setup.CallBase()` for void methods

- src/Moq/AutoImplementedPropertyGetterSetup.cs
- src/Moq/AutoImplementedPropertySetterSetup.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/Language/Flow/SetupSequencePhrase.cs
- src/Moq/MethodCall.cs
- src/Moq/Mock.cs
- src/Moq/MockException.cs
- src/Moq/SequenceSetup.cs
- src/Moq/Setup.cs
- src/Moq/SetupCollection.cs
- src/Moq/SetupWithOutParameterSupport.cs
- tests/Moq.Tests/OutRefFixture.cs
`MethodCall` represents a setup that is programmable through Moq's `Setup` API. There are, however, certain kinds of "internal" setups that are not programmable and have much simpler logic.
The intent behind this refactoring is to create a base class for all setups that has a much smaller memory footprint and contains much less logic. Internal, non-programmable setup types can then eventually be derived from that new `Setup` class.
This PR includes the conversion of `PropertyGetterMethodCall`, `PropertySetterMethodCall`, and `SequenceMethodCall` to the new & lighter-weight `Setup` base class, including renames to more precise & more consistent names:
* `PropertyGetterMethodCall` &rarr; `AutoImplementedPropertyGetterSetup`
* `PropertySetterMethodCall` &rarr; …
> Introduce new abstract base class `Setup`

- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/MethodCall.cs
- src/Moq/Setup.cs
- tests/Moq.Tests/VerifyFixture.cs
The previous refactoring (#671) has broken the combination of using `VerifyAll` followed by `VerifyNoOtherCalls` for sequence setups. This PR adds a regression test for such a scenario, and fixes it.
> Fix `VerifyAll` + `VerifyNoOtherCalls` for sequence setups

- src/Moq/Extensions.cs
- src/Moq/InvocationShape.cs
- src/Moq/MethodCall.cs
- src/Moq/MethodCallReturn.cs
- src/Moq/ParameterTypes.cs
- src/Moq/Protected/ProtectedMock.cs
There are currently several different ways in the Moq code base for comparing ordered lists of (parameter) types:
* `Enumerable.SequenceEqual`
* `Enumerable.SequenceEqual` + `AssignmentCompatibilityTypeComparer`
* `Extensions.HasSameParameterTypesAs`
* `Extensions.HasCompatibleParameterTypes`
* `Extensions.HasCompatibleParameterList`
This refactoring replaces all of the above with three new composable building blocks:
* `ParameterTypes` &mdash; wrapper for `ParameterInfo[]` so it can be treated like `Type[]`
* `Extensions.GetParameterTypes` &mdash; gets a `MethodInfo`'s parameter types as a `ParameterTypes`
* `Extensions.CompareTo` &mdash; compares any pair of `Type[]` or `ParameterTypes` using either of two comparison modes: equality, or assignment-from-compatibility.
Care has been taken …
> Replace parameter list comparison extension methods

- CHANGELOG.md
- src/Moq/Mock.cs
- tests/Moq.Tests/VerifyFixture.cs
> `Verify` exception should report configured setups for delegate mocks

- CHANGELOG.md
- src/Moq/ExpressionStringBuilder.cs
- tests/Moq.Tests/VerifyFixture.cs
> `Verify` exception should include complete call expression for delegate mocks

- CHANGELOG.md
- src/Moq/Mock.cs
- src/Moq/MockException.cs
- src/Moq/Obsolete/MockFactory.cs
- src/Moq/Properties/Resources.resx
- tests/Moq.Tests/MockRepositoryFixture.cs
Enables single call to verify no other calls on all mocks generated by the factory
Based on the discussion with @stakx in #675 it appeared that i was not using the framework correctly.
The reason i chose to do it this was way the inability to perform a `VerifyNoOtherCalls` on all mocks generated from a single factory.
This new method means you can create many mocks from a single factory, verify each expectation in turn and then at the end call `Factory.VerifyNoOtherCalls` to ensure that only the items you have verified occurred for every mock generated in a given test.
Current rather nasty workaround
```
public class MyMockRepository : MockRepository
{
public MyMockRepository(MockBehavior defaultBehavior) : base(defaultBehavior)
{
}
public virtual void VerifyNoOtherCalls()
{
VerifyMocks(m …
```
> Add VerifyNoOtherCalls to MockFactory

- tests/Moq.Tests/MockRepositoryFixture.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
- tests/Moq.Tests/StringExtensions.cs
- tests/Moq.Tests/VerifyFixture.cs
This removes all mentions of `"\r\n"`, `"\n"`, or `Environment.NewLine` from individual tests. A new helper method is used wherever multi-line string comparisons need to be performed.
> Make multi-line comparisons in tests ignorant of CRLF/LF

- src/Moq/Mock.Generic.cs
- src/Moq/Mock.cs
- tests/Moq.Tests/CallbacksFixture.cs
This PR contains support in multiple arguments.
1. Fix null reference exception in case of multiple arguments indexer.
2. Proposal for new API method SetupSetMethod which allows using It.IsAny for the indexer arguments (can be used also for properties, although existing API already covers properties). This is only in proposal level, should be enhanced (documentation, overloading for any count of indexer arguments, exceptions on illegal input).
> Support indexer with multiple arguments

- .editorconfig
- Moq.sln
- src/Moq/Extensions.cs
- tests/Moq.Tests.FSharpTypes/HasAbstractActionEvent.fs
- tests/Moq.Tests.FSharpTypes/HasAbstractEventHandlerEvent.fs
- tests/Moq.Tests.FSharpTypes/HasActionEvent.fs
- tests/Moq.Tests.FSharpTypes/IHasActionEvent.fs
- tests/Moq.Tests.FSharpTypes/IHasEventHandlerEvent.fs
- tests/Moq.Tests.FSharpTypes/Moq.Tests.FSharpTypes.fsproj
- tests/Moq.Tests/FSharpCompatibilityFixture.cs
- tests/Moq.Tests/Moq.Tests.csproj
- tests/Moq.Tests/ReflectionExtensions.cs
There are two old Google Code issues which were resolved with commit 44070a90, however no documentation or unit tests were ever added for these issues:
* **Moq fails to mock events defined in F#:**  
https://code.google.com/archive/p/moq/issues/238
* **Can't raise events on mocked Interop interfaces:**  
https://code.google.com/archive/p/moq/issues/226
This commit adds unit tests for the first of these two issues by adding an F# test project to the solution, which allows us to define F# types for use in unit tests.
Some of these tests are skipped on purpose; see https://github.com/Microsoft/visualfsharp/issues/5834.
> Add tests for Moq compatibility with F# events

- src/Moq/Language/Flow/WhenPhrase.cs
- src/Moq/Mock.Generic.cs
- src/Moq/Mock.cs
- src/Moq/Obsolete/Mock.Generic.Legacy.cs
- src/Moq/Obsolete/Mock.Legacy.cs
- src/Moq/Obsolete/ObsoleteMockExtensions.cs
- src/Moq/Protected/ProtectedAsMock.cs
- src/Moq/Protected/ProtectedMock.cs
- src/Moq/SequenceSetup.cs
This is a continuation of #663. Internal worker methods in the `Mock` class are made non-generic. The idea here is to restrict the use of generics exclusively to those places where they are useful: in the methods making up the public API. Underneath that layer, Moq should use generics as little as possible in order to avoid needless code duplication, and to make reflection easier.
> Make internal `Mock` methods non-generic

- CHANGELOG.md
- src/Moq/ExpressionExtensions.cs
- src/Moq/Extensions.cs
- src/Moq/LookupOrFallbackDefaultValueProvider.cs
- src/Moq/Mock.cs
- src/Moq/Moq.csproj
- src/Moq/Moq.nuspec
- src/Moq/SequenceSetup.cs
People are still experiencing assembly versioning problems on the .NET Framework because of the NuGet packages `System.Threading.Tasks.Extensions` and `System.ValueTuple` referenced by Moq. (See e.g. the recent #719.)
It is fairly trivial to get rid of the latter dependency... so let's get rid of it! (It means we can no longer use tuple syntax everywhere in Moq's code base, but as we haven't made excessive use of it so far, that's perhaps a small price to pay.)
> Drop `System.ValueTuple` NuGet dependency

- src/Moq/AmbientObserver.cs
- src/Moq/ExpressionExtensions.cs
- src/Moq/Extensions.cs
- src/Moq/FluentMockContext.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/Match.cs
- src/Moq/MatcherFactory.cs
- src/Moq/Mock.cs
- tests/Moq.Tests/AmbientObserverFixture.cs
- tests/Moq.Tests/CustomDefaultValueProviderFixture.cs
Moq currently cannot correctly deal with setter setups using more one matcher, e.g. when setting up an indexer's setter. This is because the `FluentMockContext` only associates at most one matcher with observed invocations.
This PR changes how `FluentMockContext` records its observations and how it lets the outside world access them. When asked for the last observed mock invocation, `FluentMockContext` now returns *all*
matchers observed immediately before the final invocation.
The class is also renamed to `AmbientObserver` (way too many things in Moq's code base are called "fluent") and documented somewhat better using XML documentation comments and tests.
> Enable `FluentMockContext` to record >1 matcher per invocation

- CHANGELOG.md
- src/Moq/Moq.csproj
- src/Moq/StringBuilderExtensions.cs
- tests/Moq.Tests/CustomMatcherFixture.cs
- tests/Moq.Tests/ExpressionExtensionsFixture.cs
- tests/Moq.Tests/MockRepositoryFixture.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
- tests/Moq.Tests/VerifyFixture.cs
added TypeNameFormatter so that richer class names could be displayed in error messages.
> address #727

- CHANGELOG.md
- src/Moq/Capture.cs
- src/Moq/ExpressionExtensions.cs
- src/Moq/It.cs
- src/Moq/Match.cs
- src/Moq/MatcherAttribute.cs
- src/Moq/MatcherFactory.cs
- tests/Moq.Tests/CustomMatcherFixture.cs
- tests/Moq.Tests/ExtensibilityFixture.cs
- tests/Moq.Tests/Linq/SupportedQuerying.cs
- tests/Moq.Tests/MatcherAttributeFixture.cs
- tests/Moq.Tests/MockFixture.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
Fixes #725 (though that is not the only reason behind this change).
> De-deprecate `[Matcher]` attribute

- CHANGELOG.md
- src/Moq/InvocationShape.cs
- tests/Moq.Tests/VerifyFixture.cs
The fix for #749. I also added a few tests to verify the derived generic parameters verification. It is already existing functionality in moq but the tests were missing. IMO it cannot be harmful anyway to add more tests.
> Verify gets confused between the same generic and non-generic signature

- CHANGELOG.md
- src/Moq/Protected/IProtectedMock.cs
- src/Moq/Protected/ProtectedMock.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
This adds a new method overload for `mock.Protected().Setup()`:
```csharp
ISetup<TMock> Setup(string voidMethodName, bool exactParameterMatch, params object[] args);
```
in addition to the existing one:
```csharp
ISetup<TMock> Setup(string voidMethodName, params object[] args);
```
This means that with a call such as the following:
```csharp
mock.Protected().Setup("SomeVoidMethod", true, arg, anotherArg);
```
`true` will be interpreted as the `exactParameterMatch` parameter instead of as the first method argument. **This can break existing code**, but it can also help new code where the `exactParameterMatch` is needed to choose the right method to be setup (e.g. fixes #735).
> Add new `mock.Protected().Setup()` method overload

- CHANGELOG.md
- src/Moq/Protected/IProtectedMock.cs
- src/Moq/Protected/ProtectedMock.cs
- tests/Moq.Tests/VerifyFixture.cs
> Add `mock.Protected().Verify` overloads with additional `exactParameterMatch` parameter

- CHANGELOG.md
- tests/Moq.Tests/VerifyFixture.cs
The previous commit #760 has fixed #703. From its description:
> 2. One example of this is when a setup for some mock member has been overridden, but there is still an `InnerMocks` entry for that same member. This typically leads to "unreachable" inner mocks being included in recursive verification when they should no longer be included.
Add tests that document this is now fixed.
(It would have been nicer to add these tests in a failing state first, but I didn't know precisely which bugs the previous refactoring would fix.)
> Document that "reachability" bug has been fixed

- CHANGELOG.md
- src/Moq/AutoImplementedPropertyGetterSetup.cs
- src/Moq/AutoImplementedPropertySetterSetup.cs
- src/Moq/IDeterministicReturnValueSetup.cs
- src/Moq/InnerMockSetup.cs
- src/Moq/MethodCall.cs
- src/Moq/Mock.cs
- src/Moq/MockException.cs
- src/Moq/MockExceptionReasons.cs
- src/Moq/Obsolete/MockFactory.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- src/Moq/SequenceSetup.cs
- src/Moq/Setup.cs
- src/Moq/StringBuilderExtensions.cs
- tests/Moq.Tests/MockRepositoryFixture.cs
Verification using `mock.Verify[All]` has always been performed in a "recursive" manner (i.e. inner mocks were verified along with the outer / owning mock). However, in the case of failure, verification would often stop and only describe the first error in the message.
This PR makes verification more thorough by aggregating verification errors at all levels:
* Mock repositories aggregate errors of all their mocks. (This was done already.)
* Mocks aggregate errors of all setups. (This is new.)
* Setups can forward errors from an inner mock. (This is also new.)
For example, given this code:
```csharp
var mock = new Mock<IOuter>();
mock.Setup(m => m.Inner.Method());
mock.Setup(m => m.AnotherMethod());
mock.VerifyAll();
```
you might now see such error message:
```
Mock<IOuter:00000001>:
This …
```
> Thorough aggregation of verification errors & more complete error messages

- src/Moq/ProxyFactories/CastleProxyFactory.cs
- src/Moq/ProxyFactories/IProxy.cs
- src/Moq/ProxyFactories/InterfaceProxy.cs
- tests/Moq.Tests/InterceptorFixture.cs
`System.Object` methods are currently not interceptable if the proxied type is an interface type, and the interceptor used is not an instance of the `Mock` class. These methods should be interceptable by all interceptors, regardless of their type.
As it happens, this requires the introduction of an `IProxy` interface which is to `IInterceptor` what `IMocked` is to `Mock`. It works in exactly the same fashion, too.
This PR might seem a bit pointless, since the only implementation of `IInterceptor` *is* the `Mock` class, so at the surface `IMocked` should suffice.
However, this lays the groundwork for my next PR, which will introduce some new machinery for converting `Action<T>` delegates back to `Expression<Action<T>>` (which is important to fix some long-standing bugs with e.g. …
> Make `System.Object` members interceptable by *any* interceptor

- src/Moq/ProxyFactories/IProxy.cs
- src/Moq/ProxyFactories/InterfaceProxy.cs
Otherwise DynamicProxy will not be able to implement it for the same reason it couldn't use `InterfaceProxy` as a proxy base class; so basically , the same explanation from 75d9d8ba applies.
> Fix `IProxy` interface visibility

- CHANGELOG.md
- src/Moq/ExpressionComparer.cs
- src/Moq/ExpressionExtensions.cs
- src/Moq/ExpressionStringBuilder.cs
- src/Moq/LambdaExpressionPart.cs
- src/Moq/Language/Flow/WhenPhrase.cs
- src/Moq/Mock.Generic.cs
- src/Moq/Mock.cs
- src/Moq/PexProtector.cs
- src/Moq/Protected/ProtectedAsMock.cs
- src/Moq/Protected/ProtectedMock.cs
- tests/Moq.Tests/ExpressionSplitFixture.cs
- tests/Moq.Tests/RecursiveMocksFixture.cs
- tests/Moq.Tests/VerifyFixture.cs
When `Setup` and `Verify` are given "recursive" / "fluent" expressions, e.g.
```csharp
mock.Setup(m => m.Foo.Bar.Baz.DoSomething())...;
```
... then up until now, Moq simply compiled that expression & executed it with `DefaultValue.Mock` temporarily enabled to set up the mock object graph leading up to `baz.DoSomething`. As elsewhere, expression compilation and execution has a variety of side effects (e.g. #699), so it would be good to avoid it.
We can actually do something fairly simple: We break apart the given expression into several setup expressions:
* `m => m.Foo`
* `(foo) => (foo).Bar`
* `(bar) => (bar).Baz`
* `(baz) => (baz).DoSomething()`
... then set these sub-expressions recursively: The original `mock` sets up the first expression to yield an inner mock of type `IBar`, who …
> Remove expression execution from `Setup` and `Verify` & make them recursive

- src/Moq/AmbientObserver.cs
- tests/Moq.Tests/AmbientObserverFixture.cs
This is required over in #768 to make expression comparison safe for `MatchExpression`s: `ExpressionComparer` might need to call `expression.IsMatch()` (which activates an `AmbientObserver`) to figure out whether an embedded expression such as `It.IsAny<T>()` is equal to a `MatchExpression`.
> Make `AmbientObserver` reentrant

- src/Moq/Evaluator.cs
- src/Moq/ExpressionComparer.cs
- src/Moq/ExpressionExtensions.cs
- src/Moq/ExpressionStringBuilder.cs
- src/Moq/It.cs
- src/Moq/Match.cs
- src/Moq/MatchExpression.cs
- tests/Moq.Tests/MatchExpressionFixture.cs
- tests/Moq.Tests/MatchFixture.cs
This is extracted from, and required by, #767. Moq should be able to process expressions containing a `MatchExpression` more or less everywhere except during compilation (because it doesn't carry enough information to properly allow that scenario).
> Make handling of `MatchExpression` more robust

- CHANGELOG.md
- src/Moq/Mock.Generic.cs
Two reasons for this:
1. It is one of the very few, if not the only, place where we do this "to keep Moq noise out" of the stack trace.
2. An earlier refactor in `InvokePreserveStack` that switched to using `ExceptionDispatchInfo` already leads to cleaner stack traces than what we had previously. It's likely the "Moq noise" is at a tolerable level now. (If it weren't, we'd have to introduce the same re-throwing pattern in all other public APIs.
Resolves #738.
> Remove catch & (re-) throw in `Raise`

- src/Moq/ExpressionExtensions.cs
- src/Moq/InvocationShape.cs
- src/Moq/Setup.cs
- src/Moq/SetupCollection.cs
Another refactoring that makes `InvocationShape` that will be needed shortly. It also permits a clearer phrasing in `SetupCollection` when a setup overrides another.
> `InvocationShape` should be equality-comparable

- src/Moq/Guard.cs
- src/Moq/InvocationShape.cs
- src/Moq/Mock.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
- tests/Moq.Tests/VerifyFixture.cs
A regression has been introduced (possibly in #765) that led to `Verify` no longer noticing attempts to verify non-overridable members. There was no unit test to catch this, so this PR adds one and fixes the problem.
> Fix regression with incomplete `Verify` expression validation

- CHANGELOG.md
- src/Moq/MockException.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
- tests/Moq.Tests/VerifyFixture.cs
Unlike `mock.Verify()` and `mock.VerifyAll()`, which look at a mock's setups, `mock.Verify(m => ...)` has absolutely no relation to setups. Listing configured setups in that method's error message can only mislead users into thinking otherwise.
This commit removes setup information from these error messages. (The list of performed invocations is of course preserved.)
>  Don't list setups in `Verify(...)` error message

- CHANGELOG.md
- src/Moq/AsInterface.cs
- src/Moq/Extensions.cs
- src/Moq/FluentMockVisitor.cs
- src/Moq/ImmutablePoppableStack.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/Invocation.cs
- src/Moq/Mock.cs
- src/Moq/MockException.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- src/Moq/ProxyFactories/CastleProxyFactory.cs
- src/Moq/ProxyFactories/InterfaceProxy.cs
- tests/Moq.Tests/InvocationsFixture.cs
- tests/Moq.Tests/RecursiveMocksFixture.cs
- tests/Moq.Tests/VerifyFixture.cs
This improves the accuracy with which Moq matches invocations against recursive / fluent verification expressions when using `mock.Verify(expression)`. Error messages likewise contain more precise & more complete information about which invocations occurred, and on what (inner) mocks.
Here's an example of what call verification error message will look like when this gets merged:
```csharp
public interface IX
{
void Do();
void Do(int arg);
IX Inner { get; }
IX GetInner(int arg);
}
var mock = new Mock<IX> { DefaultValue = DefaultValue.Mock };
mock.Object.GetInner(1).Do(1);
mock.Object.GetInner(1).Do(2);
var innerTwo = mock.Object.GetInner(2);
innerTwo.Do();
innerTwo.Do(2);
mock.Object.GetInner(3);
mock.Verify(m => m.GetInner(1).Do(It.IsAny<int>()), Times.Exactly(3));
```
```
Expected …
```
> Arguments in recursive expressions should not be treated like `It.IsAny` by default

- CHANGELOG.md
- src/Moq/ActionObserver.cs
- src/Moq/AsInterface.cs
- src/Moq/ExpressionReconstructor.cs
- src/Moq/Language/Flow/WhenPhrase.cs
- src/Moq/MethodCall.cs
- src/Moq/Mock.Generic.cs
- src/Moq/Mock.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
This adds test cases from two old issues, #430 and #432, which reveal some deficiencies in the current implementation of `ActionObserver`:
* It cannot deal with proxyable types that do not have a parameterless ctor.
* It trips up in debug mode when a base class ctor triggers virtual method calls.
This should fix both of those. Closes #430, closes #432.
> `ActionObserver` improved support for parameterized base class ctors & additional virtual calls

- CHANGELOG.md
- src/Moq/MethodCall.cs
- src/Moq/Mock.Generic.cs
- src/Moq/Moq.csproj
- src/Moq/Moq.nuspec
- src/Moq/StringBuilderExtensions.cs
- tests/Moq.Tests/MockFixture.cs
- tests/Moq.Tests/Moq.Tests.csproj
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
- tests/Moq.Tests/VerifyFixture.cs
> Add  `netstandard2.0` target

- CHANGELOG.md
- src/Moq/StringBuilderExtensions.cs
...by only showing the first 10 items of enumerables for certain safe collection types (arrays and `List<T>`). It cannot be generally assumed that `IEnumerable` actually work.
I cannot easily add the test case provided in #741 to the regression test suite as it relies on EF Core, and the test project already uses EF, so we'd likely have type conflicts if both of them are referenced.
Closes #741.
> Make `stringBuilder.AppendValueOf` safer

- CHANGELOG.md
- src/Moq/Capture.cs
- src/Moq/ExpressionExtensions.cs
- src/Moq/It.cs
- src/Moq/Match.cs
- src/Moq/Match.xdoc
- src/Moq/MatcherFactory.cs
- src/Moq/Obsolete/MatcherAttribute.cs
- tests/Moq.Tests/CustomMatcherFixture.cs
- tests/Moq.Tests/ExtensibilityFixture.cs
- tests/Moq.Tests/Linq/SupportedQuerying.cs
- tests/Moq.Tests/MatcherAttributeFixture.cs
- tests/Moq.Tests/MockFixture.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
As announced in #770, this is a partial revert of #732 in order to reduce the amount of breaking changes in the next release.
Making the `[Matcher]` attribute mandatory on *all* matchers is no longer necessary to fix #725. This is because `MatcherObserver` (which used to be `AmbientObserver`) is no longer tied into the mock interception pipeline and therefore doesn't affect their behavior, and it has been made reentrant in #769.
Closes #770.
> Re-deprecate `MatcherAttribute`

- src/Moq/Matchers/ConstantMatcher.cs
- tests/Moq.Tests/Matchers/ConstantMatcherFixture.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Make `ConstantMatcher` more (but not fully) `StackOverflowException`-proof

- CHANGELOG.md
- src/Moq/ExpressionExtensions.cs
- src/Moq/InvocationShape.cs
- src/Moq/MatcherFactory.cs
- src/Moq/Matchers/ParamArrayMatcher.cs
- src/Moq/Pair.cs
- tests/Moq.Tests/MatchExpressionFixture.cs
- tests/Moq.Tests/Matchers/AnyMatcherFixture.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
Fixes #711. See explanation in https://github.com/moq/moq4/issues/711#issuecomment-433386423 as well as in commit messages for details.
> Keep `InvocationShape` argument matchers & expressions in sync

- CHANGELOG.md
- src/Moq/MatcherFactory.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
This resolves #714.
It doesn't make sense for indexers to be matched lazily when other properties are being matched eagerly, so this will make Moq a little more consistent.
(While technically a small breaking change, making it anyway seems permissible because Moq has neglected indexers far too long and essentially left its behavior regarding them semi-unspecified.)
> Match indexers used as arguments in setup expression eagerly

- CHANGELOG.md
- src/Moq/Times.cs
- tests/Moq.Tests/TimesFixture.cs
Closes #805 (and applies some minor cleanup refactoring to `Times` while we're at it).
> Fix implementation of `Times.Equals`

- README.md
- src/Moq/Moq.nuspec
Not a framework.
In a [recent meeting of the Secret ~~GUID~~ Guild of the Mocking ~~Framework~~ Librarians](https://github.com/nsubstitute/NSubstitute/pull/545) it has been determined that Moq is actually a library, and not a framework.
This updates the README and NuGet package metadata accordingly.
> It's a library

- CHANGELOG.md
- src/Moq/Language/Flow/SetupPhrase.cs
- src/Moq/Language/Flow/SetupSequencePhrase.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
When a `Setup` fails verification, it's helpful to have the exact expression that failed, rather than the default `ToString()` representation of the `Setup` class. To illustrate:
What I'd like to see in the output message:
```C#
x => x.DoThings(null)
```
What I actually get:
```C#
Moq.Language.Flow.VoidSetupPhrase`1[Moq.Tests.Regressions.IssueReportsFixture+IFoo]
```
This PR fixes that by overriding the `ToString()` methods and calling `ToStringFixed()` on the expression that is being used. This allows for a nicely formatted string representation of the expression to be returned.
Closes #810.
> Add ToString() for fluent setup API objects

- src/Moq/SetupCollection.cs
`SetupCollection.ToArrayLive` is a fairly expensive operation and gets called more often (esp. during verification) now that inner mocks are represented as regular setups. This applies some optimizations that can easily double the speed of that operation, esp. when any overridden setups are present.
> Optimize `SetupCollection` (esp. `ToArrayLive`) for better performance

- src/Moq/Times.cs
- tests/Moq.Tests/TimesFixture.cs
See commit messages and code comments for details.
> Adjust `default(Times)` to `Times.AtLeastOnce()`

- CHANGELOG.md
- src/Moq/Mock.Generic.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Correct error message when attempting to set up an indexer with `SetupProperty`

- CHANGELOG.md
- appveyor.yml
- build/SourceLink.props
- src/Moq/Moq.csproj
We want to continue publishing SourceLink-ed debug symbols, but using classic Windows PDBs generates a huge package. Using the much smaller portable PDB format would be much better, but some people may still experience problems with those. (See e.g. GitHub issue #428.)
Let's follow the official guidance (see links below) and publish debug symbols in a separate `.snupkg` package to NuGet's symbol server. This means that we can (must, in fact) use portable PDBs as it will be the consumers' choice whether to use the separate symbols or not.
Closes #447.
References:
* https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
* https://github.com/dotnet/SourceLink#alternative-pdb-distribution
> Use portable PDB in separate NuGet symbol package

- tests/Moq.Tests/PropertiesFixture.cs
These have been made to work with the rewrites that went into 4.11.0.
> Unskip unit tests regarding indexers & matchers

- CHANGELOG.md
- src/Moq/Interception/InterceptionAspects.cs
- tests/Moq.Tests/StubExtensionsFixture.cs
Fix #835.
Was not sure, if such a minor change should be included in a changelog, but included just in case.
> Handle write-only properties in SetupAllProperties for strict mocks (fix #835)

- src/Moq/Mock.cs
- src/Moq/SetupCollection.cs
- tests/Moq.Tests/StubExtensionsFixture.cs
Fix #837.
No changelog entry here, because the fix is not against existing version, but against unreleased one.
> Fix SetupAllProperties to override pre-existing property setups (#837)

- CHANGELOG.md
- src/Moq/Linq/Mock.cs
- src/Moq/Linq/MockRepository.cs
- src/Moq/Linq/MockSetupsBuilder.cs
- src/Moq/Linq/Mocks.cs
- src/Moq/Obsolete/MockFactory.cs
- tests/Moq.Tests/Linq/MockRepositoryQuerying.cs
- tests/Moq.Tests/Linq/QueryableMocksFixture.cs
> Add LINQ to Mocks support for strict mocks

- CHANGELOG.md
- src/Moq/Interception/InterceptionAspects.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Prevent auto-stubbing failure due to inaccessible property accessors

- CHANGELOG.md
- src/Moq/Mock.cs
- tests/Moq.Tests/VerifyFixture.cs
Fixes #846. Thanks again for reporting this defect!
/cc @bash, @jnferner, @Mafii
> `VerifyNoOtherCalls`: Prevent stack overflow by remembering already verified mocks

- CHANGELOG.md
- src/Moq/MethodCall.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
- tests/Moq.Tests/ReturnsFixture.cs
See details in commit message.
This also resolves #702.
> Make return values of loose mock setups having no `.Returns` nor `.CallBase` more consistent

- CHANGELOG.md
- src/Moq/Capture.cs
- src/Moq/CaptureMatch.cs
- src/Moq/Condition.cs
- src/Moq/IMatcher.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/InvocationShape.cs
- src/Moq/Match.cs
- src/Moq/Matchers/AnyMatcher.cs
- src/Moq/Matchers/ConstantMatcher.cs
- src/Moq/Matchers/ExpressionMatcher.cs
- src/Moq/Matchers/LazyEvalMatcher.cs
- src/Moq/Matchers/MatcherAttributeMatcher.cs
- src/Moq/Matchers/ParamArrayMatcher.cs
- src/Moq/Matchers/RefMatcher.cs
- src/Moq/Setup.cs
- tests/Moq.Tests/CaptureFixture.cs
Hi.
I would like to improve the capture helper to support the following scenario:
```cs
[Fact]
public void ShouldOnlyCaptureParameterForSpecificArgumentAfterCollection()
{
var items = new List<string>();
var mock = new Mock<IFoo>();
mock.Setup(x => x.DoSomething(Capture.In(items), 1));
mock.Object.DoSomething("Hello!", 1);
mock.Object.DoSomething("World", 2);
var expectedValues = new List<string> { "Hello!" };
Assert.Equal(expectedValues, items);
}
```
This test currently fails because the capture match is evaluated on every method call, even when other matches do not pass. The goal of this PR is to perform the capture only after all parameter match were successfully evaluated.
The current implementation is a proposal and I am clearly open to suggestions or improvements ideas.
> Proposal: Prevent capturing arguments on match failure

- CHANGELOG.md
- src/Moq/ExpressionStringBuilder.cs
- src/Moq/Guard.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/MethodCall.cs
- src/Moq/Mock.Generic.cs
- src/Moq/Mock.Generic.xdoc
- src/Moq/Mock.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- src/Moq/SetupCollection.cs
- src/Moq/StringBuilderExtensions.cs
- tests/Moq.Tests/MockFixture.cs
- tests/Moq.Tests/MockedEventsFixture.cs
Hi,
I was busy during the weekend with this feature, it adds the functionality to Setup and Verify events as all other methods. I tried to preserve backward compatibility and also I have added new test scenarios to verify this feature. Four new methods have been added (I am maybe thinking of merging this to `SetupEvent` and `VerifyEvent`):
`SetupAdd`
`SetupRemove`
`VerifyAdd`
`VerifyRemove`
Besides these methods `Verify()`, `VerifyAll()` and `VerifyNoOtherCalls` work as well. 
Kind regards,
Nikola
> #825 event handlers setup and verify

- CHANGELOG.md
- src/Moq/Extensions.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
Fixes #870 and likely also #869.
> Fix `SetupAllProperties` for properties whose name starts with `Item`

- CHANGELOG.md
- src/Moq/MockDefaultValueProvider.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> fix: Don't attempt to set CallBase on auto-generated mocks for delegates

- CHANGELOG.md
- src/Moq/MethodCall.cs
- tests/Moq.Tests/AfterReturnCallbackDelegateValidationFixture.cs
This is in response to, and closes, #872.
There's currently an inconsistency regarding how `Callback` delegates are validated: In the post-`Returns` position, validation is very relaxed, while it's more strict in a pre-`Returns` or no-`Returns` scenario.
This makes `Callback` delegate validation strict regardless of `Callback`'s position in the setup.
> Make post-`Returns` callback delegate validation more strict

- src/Moq/Extensions.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Fix `SetupAllProperties` for properties named `Item`

- CHANGELOG.md
- src/Moq/InvocationCollection.cs
- src/Moq/MethodCall.cs
- src/Moq/Mock.Generic.cs
- src/Moq/Setup.cs
- src/Moq/SetupCollection.cs
- tests/Moq.Tests/InvocationsFixture.cs
> Let `mock.Invocations.Clear()` remove traces of earlier invocations more thoroughly

- src/Moq/Extensions.cs
- src/Moq/MethodCall.cs
- src/Moq/StringBuilderExtensions.cs
- tests/Moq.Tests/StringBuilderExtensionsFixture.cs
This ensures that `in`, `ref`, `out`, and `params` modifiers are included in the formatting of parameter type lists.
> Format method parameter type list more accurately

- src/Moq/ExpressionStringBuilder.cs
- tests/Moq.Tests/ExpressionStringBuilderFixture.cs
In some cases, `ExpressionStringBuilder` will format an indexer assignment expression `x => x[i1, i2] = v` incorrectly as `x => x[i1, i2, v] = v`.
> Fix `ExpressionStringBuilder` formatting of indexer assignment

- src/Moq/ExpressionStringBuilder.cs
- tests/Moq.Tests/ExpressionStringBuilderFixture.cs
... by including the `?` and `:` characters in the formatted output.
> Fix `ExpressionStringBuilder` formatting of ternary conditional operator

- CHANGELOG.md
- src/Moq/Unwrap.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
... because not all completed `Task`s have successfully produced a `.Result`!
This fixes #883.
> Fix too-optimistic Task unwrapping logic in `Unwrap`

- src/Moq/SequenceSetup.cs
- tests/Moq.Tests/InvocationsFixture.cs
> Uninvoke `SequenceSetup` on `mock.Invocations.Clear()`

- src/Moq/InnerMockSetup.cs
- tests/Moq.Tests/InvocationsFixture.cs
> Uninvoke `InnerMockSetup` on `mock.Invocations.Clear()`

- CHANGELOG.md
- src/Moq/Expressions/Visitors/UpgradePropertyAccessorMethods.cs
- src/Moq/Extensions.cs
- src/Moq/Guard.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/Invocation.cs
- src/Moq/MatcherFactory.cs
- src/Moq/Mock.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- src/Moq/SetupCollection.cs
- src/Moq/StringBuilderExtensions.AppendExpression.cs
- tests/Moq.Tests/ComCompatibilityFixture.cs
- tests/Moq.Tests/FSharpCompatibilityFixture.cs
- tests/Moq.Tests/PropertiesFixture.cs
> Fix `SetupAllProperties` indexer regression & refactor accessor check methods for clarify

- CHANGELOG.md
- src/Moq/MatcherFactory.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
- tests/Moq.Tests/UnmatchableMatchersFixture.cs
> Fail when implicit conversion operator renders argument matcher unmatchable

- CHANGELOG.md
- src/Moq/Extensions.cs
- src/Moq/Invocation.cs
- src/Moq/InvocationShape.cs
- src/Moq/ProxyFactories/CastleProxyFactory.cs
- src/Moq/ProxyFactories/InterfaceProxy.cs
- tests/Moq.Tests/AsInterfaceFixture.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
This replaces the machinery that was responsible for determining whether an invoked method matches that encoded in a setup or verification expression. This previous machinery is very ad-hoc and performs a bunch of tests, such as method name equality, assignment compatibility, and parameter list equality. 
Instead of all that, why not let the runtime do that work by leveraging `method.GetBaseDefinition()`, then simply comparing `MethodInfo`s? (There are some finer points, such as converting generic methods to their (open) generic method definitions; mapping interface methods to the concrete proxy type's methods that provide their implementations; special handling for delegate invocations; etc.)
Fixes #657. Supercedes #658. Fixes #903.
> New algorithm for matching invoked methods against expected methods

- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
which demonstrates that Moq no longer cares about the precise return type of methods if they otherwise match. This enables some scenarios involving generic methods that previously weren't supported.
(It seems correct that Moq no longer tries to match method's return types exactly. While technically not incorrect, it is unusual behavior for most people coming from VB.NET or C#, where the return type is not
considered part of the method signature WRT method resolution.)
/cc @oddbear who originally came up with that test
> Add test from #343 to regression test suite

- src/Moq/It.cs
- src/Moq/Match.cs
- tests/Moq.Tests/Matchers/IsAssignableFromVsIsOperatorFixture.cs
I've long been bothered by the convoluted conditions inside `It.IsAny<T>` and `Matcher.Matches` (which gets executed just before the former). These can be simplified & easier to understand.
> Simplify code in `Match.Matches` and `It.IsAny<T>`

- CHANGELOG.md
- src/Moq/EventHandlerCollection.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/Mock.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
With this PR, Moq starts identifying events by their full `EventInfo` instead of just by their name.
This was originally planned for version 4.13.1, but since we're adding functionality to setup & verify event subscription / unsubscription in 4.13.0, it will become possible (and more likely) that users work with events more often. Therefore event identification should be reasonably accurate, or we'll just receive unnecessary bug reports.
Fixes #893.
> Improve precision of event accessor method resolution

- CHANGELOG.md
- src/Moq/ReturnsExtensions.Generated.cs
- src/Moq/ReturnsExtensions.cs
- src/Moq/ReturnsExtensions.tt
- tests/Moq.Tests/ReturnsExtensionsFixture.cs
... so `null` is treated as the intended result, not as a lambda function null reference.
Resolves #909.
> Add special handling for `.ReturnsAsync(null)`

- CHANGELOG.md
- src/Moq/ExpressionExtensions.cs
- tests/Moq.Tests/HidePropertyFixture.cs
mock.Setup(m => m.Prop) throws AmbiguousMatchException in case that:
* Prop hides the property with *new* keyword;
* the hidden and the derived properties have different types;
* mocked object has the child class of the class, where the property was hidden.
You can repropduce the exception with the following code:
public class HidePropertyFixture
{
public class A
{
public string Prop { get; }
}
public class B : A
{
// consider new keyword and the different type of property
public new virtual int Prop { get; }
}
public class C : B
{
}
[Fact]
public void SetupsDerivedProperty()
{
// create the mock of C; mock of B works correct
var mock = new Mock<C>();
// the next line will throw AmbiguousMatchException 
mock.Setup(m => m.Prop);
}
}
Stacktrace:
System.Reflection.AmbiguousMatchException
в …
> AmbiguousMatchException when setting up the property, that hides another one

- CHANGELOG.md
- src/Moq/ProxyFactories/InterfaceProxy.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Use correct proxy type in `InterfaceProxy`

- CHANGELOG.md
- src/Moq/InvocationShape.cs
- tests/Moq.Tests/InvocationShapeFixture.cs
- tests/Moq.Tests/RecursiveMocksFixture.cs
... which is how Moq treats these arrays in other parts, but currently not in recursive setup/verification expressions.
Fixes #946.
> Match `params` arrays in setup/verification expressions using structural equality

- CHANGELOG.md
- src/Moq/Extensions.cs
- src/Moq/Interception/InterceptionAspects.cs
- tests/Moq.Tests/ExtensionsFixture.cs
- tests/Moq.Tests/StubExtensionsFixture.cs
Fixes #886.
The newly introduced helper extension methods `property.CanRead(out MethodInfo getter)` and `property.CanWrite(out MethodInfo setter)` may also be applicable elsewhere in the code base where we currently use `property.CanRead` and `property.CanWrite`. Care should be taken when replacing the latter with the former as this might change the code's semantics.
> Ensure `SetupAllProperties` stubs all accessors of partially overridden properties

- CHANGELOG.md
- src/Moq/Linq/Mock.cs
- tests/Moq.Tests/InvocationsFixture.cs
[This hack](https://github.com/moq/moq4/blob/0d913b9ba527e7b480b0ae3d47ac3016d9ec11e6/src/Moq/Linq/Mock.cs#L72-L82) introduced by yours truly in #543 has introduced inconsistent behavior between `new Mock<T>()` and `Mock.Of<T>()`: The latter will clear *all* invocations from the mock's `Invocations` collection &mdash; not just those caused by the library itself (as was intended), but also those caused by user code.
We can now safely remove that hack since we no longer use `FluentMockVisitor` (which was the component causing extraneous invocations).
> `Mock.Of<Class>` shouldn't delete invocations made from `Class`' ctor

- src/Moq/AutoImplementedPropertyGetterSetup.cs
- src/Moq/AutoImplementedPropertySetterSetup.cs
- src/Moq/InnerMockSetup.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/Invocation.cs
- src/Moq/MethodCall.cs
- src/Moq/Mock.cs
- src/Moq/SequenceSetup.cs
- src/Moq/Setup.cs
- tests/Moq.Tests/VerifyFixture.cs
This is a prerequisite to #976, as it gets the setup verification API ready for publication.
Besides simplifying existing code, it also opens doors to new future forms of verification besides just `mock.Verify()` and `mock.VerifyAll()`&mdash;think `mock.Verify(setup => setup.State.Contains(<some tag>)`.
/cc @ashmind
> Make verification API more generic than `Verify()`, `VerifyAll()`

- CHANGELOG.md
- src/Moq/AsInterface.cs
- src/Moq/ISetup.cs
- src/Moq/ISetupList.cs
- src/Moq/InnerMockSetup.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/InvocationCollection.cs
- src/Moq/Mock.Generic.cs
- src/Moq/Mock.cs
- src/Moq/MockExtensions.cs
- src/Moq/Setup.cs
- src/Moq/SetupCollection.cs
- tests/Moq.Tests/MockFixture.cs
- tests/Moq.Tests/SetupFixture.cs
- tests/Moq.Tests/SetupsFixture.cs
This exposes a mock's `Setups` collection in the public API. Setups accessible via that (for now read-only) collection are of type `ISetup` and (for now) have three properties that describe some basic aspects of each setup:
* `Expression`
* `IsConditional`
* `IsOverridden`
This PR will be followed by a couple more that add more advanced functionality, e.g. to navigate the mock-setup or setup-setup object graph, and to perform custom verification.
> Expose `Mock.Setups`, part 1: Basics

- CHANGELOG.md
- src/Moq/AutoImplementedPropertyGetterSetup.cs
- src/Moq/AutoImplementedPropertySetterSetup.cs
- src/Moq/IInvocation.cs
- src/Moq/ISetup.cs
- src/Moq/InnerMockSetup.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/Invocation.cs
- src/Moq/InvocationCollection.cs
- src/Moq/MethodCall.cs
- src/Moq/MockException.cs
- src/Moq/SequenceSetup.cs
- src/Moq/Setup.cs
- src/Moq/SetupCollection.cs
- tests/Moq.Tests/InvocationsFixture.cs
- tests/Moq.Tests/SetupFixture.cs
This allows you...
* to distinguish between unmatched setups and those that were matched by at least one invocation via the `ISetup.WasMatched { get; }` boolean property; and
* to find out whether an invocation matched a setup (and which one) via the `IInvocation.WasMatched(out ISetup matchingSetup)` method.
> Expose `Mock.Setups`, part 2: Match status of setups & invocations

- src/Moq/AutoImplementedPropertyGetterSetup.cs
- src/Moq/AutoImplementedPropertySetterSetup.cs
- src/Moq/Setup.cs
- tests/Moq.Tests/VerifyFixture.cs
(The two unit tests wouldn't have failed in Moq version 4.13.1. Strange we didn't have any tests for this scenario.)
> Fix regression when verifying `SetupAllProperties`' setups

- CHANGELOG.md
- src/Moq/AutoImplementedPropertyGetterSetup.cs
- src/Moq/AutoImplementedPropertySetterSetup.cs
- src/Moq/IInvocation.cs
- src/Moq/ISetup.cs
- src/Moq/InnerMockSetup.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/Invocation.cs
- src/Moq/Language/Flow/SetupPhrase.cs
- src/Moq/MethodCall.cs
- src/Moq/Mock.cs
- src/Moq/SequenceSetup.cs
- src/Moq/Setup.cs
- src/Moq/SetupWithOutParameterSupport.cs
- tests/Moq.Tests/SetupFixture.cs
- tests/Moq.Tests/VerifyFixture.cs
This adds `void Verify(bool recursive = true)` and `void VerifyAll()` methods to `ISetup`.
> Expose `Mock.Setups`, part 3: Individual setup verification

- CHANGELOG.md
- src/Moq/AutoImplementedPropertyGetterSetup.cs
- src/Moq/AutoImplementedPropertySetterSetup.cs
- src/Moq/FluentSetup.cs
- src/Moq/IFluentSetup.cs
- src/Moq/ISetup.cs
- src/Moq/InnerMockSetup.cs
- src/Moq/MethodCall.cs
- src/Moq/Mock.cs
- src/Moq/MockException.cs
- src/Moq/SequenceSetup.cs
- src/Moq/Setup.cs
- src/Moq/SetupWithOutParameterSupport.cs
- tests/Moq.Tests/SetupFixture.cs
This adds one new property and two new methods to `ISetup`:
* `Mock Mock { get; }` to find the mock to which a setup belongs;
* `bool? ReturnsMock(out Mock innerMock)` to get at a setup's inner mock (e.g. when doing recursive verification);
* `bool IsPartOfFluentSetup(out IFluentSetup fluentSetup)` to get at the original "fluent" setup expression for those setups that have been split apart into many setups on several mocks.
This will very likely conclude this series of PRs.
> Expose `Mock.Setups`, part 4: Mock, fluent setup & inner mock discovery

- src/Moq/MethodCall.cs
- tests/Moq.Tests/ReturnsDelegateValidationFixture.cs
> Allow `Func<IInvocation,>` callback with `Returns`

- CHANGELOG.md
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- src/Moq/Setup.cs
- tests/Moq.Tests/VerifyFixture.cs
> Make `conditionalSetup.Verifiable()` an error

- CHANGELOG.md
- src/Moq/ExpressionComparer.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Evaluate captured variables during expression tree comparison

- src/Moq/SetupCollection.cs
- tests/Moq.Tests/ItIsAnyTypeFixture.cs
This would have caused a regression before version 4.13, but appears to work now&mdash;and should result in improved performance due to the reduced amount of matching performed.
> Stop searching for setup when first match found

- CHANGELOG.md
- src/Moq/SequenceExtensions.cs
- tests/Moq.Tests/SequenceExtensionsFixture.cs
Added method overloads to ISetupSequentialResult PassAsync and ThrowsAsync for async methods with void return
> Added method overloads to ISetupSequentialResult async void methods

- src/Moq/MethodCall.cs
(This was triggered by the addition of a missing call to `invocation.Return()` in order to terminate a `void` method `Invocation`.)
> Clean up setup execution method

- CHANGELOG.md
- src/Moq/Mock.cs
- src/Moq/Setup.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Prevent stack overflow when verifying cyclic mock object graph

- CHANGELOG.md
- src/Moq/Interception/InterceptionAspects.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
This regression is due to a refactoring of `MethodCall.ExecuteCore`, most likely #1013.
Fixes #1024.
> `DefaultValue.Mock` should not add redundant setups for already-matched invocations

- src/Moq/ProxyFactories/CastleProxyFactory.cs
The [attributes that we're adding to `AttributesToAvoidReplicating`](https://github.com/moq/moq4/blob/baa2a9ef4b8dd7def55f200d51bb4fe979d77a10/src/Moq/ProxyFactories/CastleProxyFactory.cs#L38-L48) are [already registered by DynamicProxy itself](https://github.com/castleproject/Core/blob/f0626e2cb2a8df9da113bed8abcbfc7d50631d63/src/Castle.Core/DynamicProxy/Generators/AttributesToAvoidReplicating.cs#L32-L39). (Security attributes don't need to be registered separately; registering the common base type `SecurityAttribute` is sufficient.)
Closes #1026.
> No longer need to use `AttributesToAvoidReplicating`

- CHANGELOG.md
- src/Moq/Evaluator.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
This might fix #1031.
This is not the best possible solution. It would be preferable to require matchers to carry an easily discoverable `[Matcher]` attribute, such that expressions don't have to be compiled and executed anymore just to discover whether a matcher ran. (Requiring that attribute would be a breaking change, which perhaps we can avoid for a little while longer.)
> Expression execution during override detection must not stop setup from being added

- src/Moq/Extensions.cs
- src/Moq/MethodCall.cs
This is a preparatory step that will facilitate the introduction to behavior-driven setups.
> Simplify `MethodCall`'s response types

- CHANGELOG.md
- src/Moq/ExpressionExtensions.cs
- src/Moq/InvocationShape.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Fix `NullReferenceException` when using write-only indexer with `VerifySet`

- CHANGELOG.md
- src/Moq/ExpressionExtensions.cs
- src/Moq/InvocationShape.cs
- src/Moq/Linq/Mocks.cs
- src/Moq/Mock.cs
- tests/Moq.Tests/ExpressionSplitFixture.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Fix setting of nested non-overridable properties via `Mock.Of`

- CHANGELOG.md
- src/Moq/It.cs
- tests/Moq.Tests/CustomTypeMatchersFixture.cs
- tests/Moq.Tests/MatchersFixture.cs
> Implement It.Is, It.IsIn, It.IsNotIn with a comparer overload

- src/Moq/Moq.csproj
- tests/Moq.Tests.FSharpTypes/Moq.Tests.FSharpTypes.fsproj
- tests/Moq.Tests.VisualBasic/Moq.Tests.VisualBasic.vbproj
- tests/Moq.Tests/Moq.Tests.csproj
This should make it possible to build Moq on machines using `dotnet` even when Visual Studio is not installed.
(Reference assemblies for the .NET Framework used to be only available on your machine if you installed Visual Studio, but now they have been made available through a NuGet package.)
**Things left to do:**
> Add .NET Framework reference assembly packages

- CHANGELOG.md
- src/Moq/MatcherFactory.cs
- tests/Moq.Tests.VisualBasic/IssueReports.vb
This should fix #1067.
I'll probably have to run a few more checks on whether it's really safe to blindly remove all type conversion nodes in `MatcherFactory` before merging this.
> Remove superfluous `Convert` nodes added by VB.NET in cases involving constrained generic type parameters

- CHANGELOG.md
- src/Moq/MockDefaultValueProvider.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
This should fix #1071.
**Note:** While this introduces a small breaking change (at least in theory), it is one that fulfills a promise made by the pre-existing XML documentation for `SetupAllProperties`:
https://github.com/moq/moq4/blob/947c6a0aa1bbf265b5555ad0a84beb5bfc53b4e2/src/Moq/Mock.Generic.cs#L671-L674
> Make `DefaultValue.Mock` inherit property stubbing

- CHANGELOG.md
- src/Moq/InnerMockSetup.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
This fixes #1073.
(Moq's recursive verification is a pain to get right, so I am half expecting this to break something else. Hopefully, we'll soon be able to replace recursive verification with a better ownership rule&mdash;"mocks own setups, not other mocks"&mdash;see https://github.com/moq/moq4/issues/1018#issuecomment-652265316.)
> Don't require inner mock setups to be matched

- CHANGELOG.md
- src/Moq/Linq/MockSetupsBuilder.cs
- tests/Moq.Tests/ComCompatibilityFixture.cs
> Make `Mock.Of<>` work with COM interop types that are annotated with `[CompilerGenerated]`

- CHANGELOG.md
- src/Moq/IInvocation.cs
- src/Moq/Invocation.cs
- src/Moq/InvocationExceptionWrapper.cs
- src/Moq/ProxyFactories/CastleProxyFactory.cs
- tests/Moq.Tests/InvocationsFixture.cs
> Add exception property to IInvocation

- CHANGELOG.md
- src/Moq/ExpressionExtensions.cs
- src/Moq/Extensions.cs
- tests/Moq.Tests/StubExtensionsFixture.cs
> Fix `SetupProperty` for split properties (where mocked type overrides only the getter)

- CHANGELOG.md
- src/Moq/ExpressionComparer.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
>  Evaluate all captured variables when comparing LINQ expressions 

- CHANGELOG.md
- src/Moq/Interception/Mock.cs
- tests/Moq.Tests/EventHandlersFixture.cs
> Always record calls to += and -= event accessors

- CHANGELOG.md
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/Interception/Mock.cs
- src/Moq/MethodCall.cs
- src/Moq/SetupCollection.cs
- tests/Moq.Tests/EventHandlersFixture.cs
- tests/Moq.Tests/MockFixture.cs
... which was documented in a preceding PR (#1082).
> Simplify event subscription and remove a remaining inconsistency

- CHANGELOG.md
- src/Moq/Linq/MockSetupsBuilder.cs
- tests/Moq.Tests/Linq/QueryableMocksFixture.cs
> Enable parameterized `Mock.Of<>` in query comprehension `from` clause 

- README.md
Discord has several benefits over gitter and is now the de-facto place for other Microsoft large-scale projects (i.e. https://cs.dotnet.gg/)
I'm there now most of the time, so selfishly, I'd like to move this over too :)
> Add Discord channel link to improve the experience over Gitter

- CHANGELOG.md
- src/Moq/ExpressionExtensions.cs
- src/Moq/Extensions.cs
- src/Moq/It.cs
- tests/Moq.Tests/CustomTypeMatchersFixture.cs
- tests/Moq.Tests/Moq.Tests.csproj
- tests/Moq.Tests/NestedTypeMatchersFixture.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Add support for nested type matchers

- CHANGELOG.md
- src/Moq/Moq.csproj
Fix for issue https://github.com/moq/moq4/issues/1107
> Updating System.Threading.Tasks.Extensions to 4.5.4

- src/Moq/Guard.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
Modified Exception message to include the type name. 
Fixes #1112
> Changed TypeNotMockable exception message

- CHANGELOG.md
- src/Moq/SetupCollection.cs
- tests/Moq.Tests/MockFixture.cs
I've played with the code a bit this morning and this change fixes the unittests I've added (at the cost of a bit of extra memory consumption and an extra operation always to save n operations in most cases)
fixes #1110
> Fix for slow down with many setups on single mock

- CHANGELOG.md
- src/Moq/Mock.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- src/Moq/Setup.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
- tests/Moq.Tests/VerifyFixture.cs
> Allow marking conditional setups as `.Verifiable()` once again

- src/Moq/AutoImplementedPropertyGetterSetup.cs
- src/Moq/AutoImplementedPropertySetterSetup.cs
- src/Moq/InnerMockSetup.cs
- src/Moq/Mock.cs
- src/Moq/Setup.cs
This makes code both shorter and more consistent with the existing code pattern used in `MockRepository`.
> Abandon 'Try' pattern in verification methods

- CHANGELOG.md
- src/Moq/ActionObserver.cs
- src/Moq/Async/AwaitExpression.cs
- src/Moq/Async/AwaitableFactory`1.cs
- src/Moq/Async/AwaitableFactory`2.cs
- src/Moq/Async/IAwaitableFactory.cs
- src/Moq/Async/TaskFactory.cs
- src/Moq/Async/TaskFactory`1.cs
- src/Moq/Async/ValueTaskFactory.cs
- src/Moq/Async/ValueTaskFactory`1.cs
- src/Moq/ExpressionExtensions.cs
- src/Moq/Invocation.cs
- src/Moq/InvocationShape.cs
- src/Moq/Setup.cs
- tests/Moq.Tests/SetupTaskResultFixture.cs
This much more focused version of #1123 only covers setting up the `.Result` of (value) task-based async methods.
* The dedicated async setup methods `.ReturnsAsync`, `.ThrowsAsync` etc. are now largely superfluous:
```diff
-mock.Setup(x => x.GetFooAsync()).ReturnsAsync(foo)
+mock.Setup(x => x.GetFooAsync().Result).Returns(foo)
```
From a user perspective, setups become more uniform in shape. From a maintainer's perspective, we have less work. More specifically, we no longer need to ensure that those async setup verbs are at feature parity with their non-async counterparts.
* It adds async support where such async verbs aren't currently available:
```diff
-Mock.Of<X>(x => x.GetFooAsync() == Task.FromResult(foo))
+Mock.Of<X>(x => x.GetFooAsync().Result == foo)
```
but also in other places …
> Add ability to set up the `.Result` of (value) tasks

- src/Moq/Moq.csproj
- tests/Moq.Tests/MatchExpressionFixture.cs
Since v5 is not released as an official nuget package yet I'm pushing this minor update to the v4 repo instead.
Contains:
* Added netstandard2.1 to TargetFrameworks
Additional:
* Make unit test language invariant
In order to test my changes I ran the unit tests and noticed a language depending unit test. Instead it is now based on the stack trace which makes this language invariant.
Fixes #1041 
I'm not too sure if this minor fix actually requires an entry to the changelog. If you want me to add one, please say so.
> Multitarget .NET Standard 2.1

- CHANGELOG.md
- src/Moq/Interception/InterceptionAspects.cs
- tests/Moq.Tests.VisualBasic/IssueReports.vb
fix(vb): Indexer properties raise AmbiguousMatchException.
Fixes #1129.
> Avoid `AmbiguousMatchException` when interface has indexer besides property

- CHANGELOG.md
- src/Moq/Behaviors/ReturnBaseOrDefaultValue.cs
- src/Moq/Moq.csproj
- src/Moq/Pair.cs
- src/Moq/ProxyFactories/CastleProxyFactory.cs
- tests/Moq.Tests/CallBaseDefaultInterfaceImplementationsFixture.cs
- tests/Moq.Tests/Moq.Tests.csproj
- tests/Moq.Tests/ProxyFactories/MostSpecificOverrideFixture.cs
As of version 4.4.0, DynamicProxy is not able to reliably `.Proceed()` to a base method implementation if it is provided by an interface. From a user perspective, one would likely try to invoke a default interface implementation using `.CallBase()`.
This is an attempt to work around this current DynamicProxy limitation by performing the non-virtual call to the interface method manually. This involves some System.Reflection.Emit code inspired by @thomaslevesque's approach mentioned in https://github.com/castleproject/Core/issues/447#issuecomment-536274305.
~~This works mostly, except for one important detail: Moq will always call the least specific default implementation, instead of the most specific one. (This matters when one overrides a default implementation in a derived interface, …
> `.CallBase` for default interface implementations

- CHANGELOG.md
- src/Moq/MethodCall.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- tests/Moq.Tests/SetupTaskResultFixture.cs
> Fix type mismatch during callback validation for task `.Result` setups

- CHANGELOG.md
- src/Moq/StringBuilderExtensions.AppendExpression.cs
- tests/Moq.Tests/VerifyFixture.cs
> Improve error message when verification fails

- CHANGELOG.md
- src/Moq/MethodCall.cs
- tests/Moq.Tests/CallbacksFixture.cs
Fixes a problem mentioned in https://github.com/moq/moq4/issues/1139#issuecomment-771563898.
> Ensure `Returns(InvocationFunc)` doesn't throw `TargetInvocationException`

- CHANGELOG.md
- src/Moq/ExpressionExtensions.cs
- tests/Moq.Tests.VisualBasic/IssueReports.vb
> Fix `InvalidOperationException` when mocking class with overloaded property/indexer in base class

- CHANGELOG.md
- src/Moq/Protected/ProtectedAsMock.cs
- tests/Moq.Tests/ProtectedAsMockFixture.cs
Fix #1162 
As per https://github.com/moq/moq4/pull/1165#discussion_r672094882
> Fix virtual properties and automocking for `mock.Protected().As<>()`

- CHANGELOG.md
- src/Moq/Protected/ProtectedMock.cs
- tests/Moq.Tests/ProtectedMockFixture.cs
> Use `value` argument in `mock.Protected().SetupSet` and `...VerifySet`

- CHANGELOG.md
- src/Moq/Behaviors/ThrowComputedException.cs
- src/Moq/Language/Flow/SetupPhrase.cs
- src/Moq/Language/Flow/SetupSequencePhrase.cs
- src/Moq/Language/ISetupSequentialAction.cs
- src/Moq/Language/ISetupSequentialResult.cs
- src/Moq/Language/IThrows.Generated.cs
- src/Moq/Language/IThrows.cs
- src/Moq/Language/IThrows.tt
- src/Moq/MethodCall.cs
- src/Moq/Moq.csproj
- tests/Moq.Tests/SequentialActionExtensionsFixture.cs
- tests/Moq.Tests/SetupTaskResultFixture.cs
- tests/Moq.Tests/ThrowsFixture.cs
This implements https://github.com/moq/moq4/issues/1048 (In `Throws`, we discussed in https://github.com/moq/moq4/pull/1190 that we would leave `ThrowsAsync` alone for now).
The existing method `SetReturnComputedValueBehavior` in `MethodCall.cs` is slightly refactored so that those functions the new `SetThrowComputedExceptionBehavior` needs are available, some bits were not needed. I tried to find a balance here between duplication and the new function having its slightly different path and checks, but am more than happy to tweak this as needed. The diff here isn't great, probably better viewed side by side.
> Add new Throws overloads that allow arguments to be passed to it

- CHANGELOG.md
- src/Moq/Protected/ProtectedMock.cs
- tests/Moq.Tests/ProtectedMockFixture.cs
> fix ProtectedMock fails when arguments are of type Expression #1188

- src/Moq/Behaviors/ReturnBaseOrDefaultValue.cs
- src/Moq/Expectation.cs
- src/Moq/ExpressionExtensions.cs
- src/Moq/Extensions.cs
- src/Moq/ISetup.cs
- src/Moq/InnerMockSetup.cs
- src/Moq/MethodCall.cs
- src/Moq/MethodExpectation.cs
- src/Moq/MethodSetup.cs
- src/Moq/Mock.cs
- src/Moq/SequenceSetup.cs
- src/Moq/Setup.cs
- src/Moq/SetupCollection.cs
- src/Moq/SetupWithOutParameterSupport.cs
- src/Moq/StubbedPropertyGetterSetup.cs
- src/Moq/StubbedPropertySetterSetup.cs
- tests/Moq.Tests/MethodExpectationFixture.cs
This refactoring enables setups that handle more than just a single method.
I'm have two use cases in mind:
1. `StubbedPropertyGetterSetup` and `StubbedPropertySetterSetup` could be merged into a single setup type. This would be more efficient than what we have now, and also better capture the semantics of a call to `mock.SetupProperty()`.
2. It would allow creation of a new setup type `StubbedPropertiesSetup` backing `mock.SetupAllProperties()`. This would be added on `mock.SetupAllProperties()` and keep track of any number of properties' values. Again, this would be more efficient than the current solution, allow us to get rid of some convoluted internal bits (such as [`SetupCollection.RemoveAllPropertyAccessorSetups`](https://github.com/moq/moq4/blob/eacd7571c063fb458072289dfd40f708a8a2 …
> Enable multi-method setups

- src/Moq/MethodCall.cs
- src/Moq/Properties/Resources.Designer.cs
- src/Moq/Properties/Resources.resx
- tests/Moq.Tests/ItIsAnyTypeFixture.cs
> Disallow use of type matchers in `.Callback` and `.Returns`

- CHANGELOG.md
- src/Moq/Matchers/LazyEvalMatcher.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Use same comparison logic in `LazyEvalMatcher` as in `ConstantMatcher`

- CHANGELOG.md
- src/Moq/AsInterface.cs
- src/Moq/Interception/InterceptionAspects.cs
- src/Moq/Interception/Mock.cs
- src/Moq/Linq/MockSetupsBuilder.cs
- src/Moq/Linq/Mocks.cs
- src/Moq/Mock.cs
- src/Moq/MockDefaultValueProvider.cs
- src/Moq/Mock`1.cs
- src/Moq/SetupCollection.cs
- src/Moq/StubbedPropertiesSetup.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
- tests/Moq.Tests/SetupFixture.cs
- tests/Moq.Tests/SetupsFixture.cs
This is a continuation of #1204, where a dedicated setup type was created for single stubbed properties' accessors (i.e. `SetupProperty`). Thanks to #1203, the same can also be done for `SetupAllProperties`.
A few additional notes:
* This gets rid of the `RemoveAllPropertyAccessorSetups` method in `SetupCollection`, restoring it to an add-only collection, which in turn means its use of `lock`-ing could be optimized in a similar fashion as was done for `InvocationCollection`.
* Gets rid of the `AutoSetupPropertiesDefaultValueProvider` hack and simplifies the interception pipeline.
* Moq should become a little more efficient in principle, since there will be fewer setups created overall.
Fixes #1066, likely fixes #1231.
> Create dedicated setup type for `SetupAllProperties`

- CHANGELOG.md
- src/Moq/Mock.cs
- src/Moq/Mock`1.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Make `SetupProperty` work with recursive expressions again

- src/Moq/Interception/CastleProxyFactory.cs
> Fixed missing placeholder in exception message Resources.TypeNotMockable

- CHANGELOG.md
- src/Moq/MethodExpectation.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Account for by-ref params in `MethodExpectation.CreateFrom(Invocation)`

- CHANGELOG.md
- appveyor.yml
- src/Moq/Moq.csproj
- tests/Moq.Tests.FSharpTypes/Moq.Tests.FSharpTypes.fsproj
- tests/Moq.Tests.VisualBasic/Moq.Tests.VisualBasic.vbproj
- tests/Moq.Tests/Moq.Tests.csproj
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Upgrade DynamicProxy to version 5.0.0

- CHANGELOG.md
- src/Moq/StubbedPropertySetup.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Make `StubbedPropertySetup.IsMatch` less picky

- README.md
It is now officially at http://moq.github.io/moq4/
Supports #1244.
> Update link to documentation website

- src/Moq/Moq.csproj
Add System.Threading.Tasks.Extensions reference conditionally to reduce dependencies on newer frameworks.
> add STTE for older target frameworks only

- CHANGELOG.md
- src/Moq/Moq.csproj
- tests/Moq.Tests/Moq.Tests.csproj
- tests/Moq.Tests/RecordsFixture.cs
> Upgrade DynamicProxy to version 5.1.0 for better `record` type support

- CHANGELOG.md
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
Closes #1175. (That problem got fixed by the DynamicProxy upgrade in #1275.)
> Add regression tests for subscribing to & raising redeclared event

- CHANGELOG.md
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
Closes #1209. (This particular issue was fixed by the DynamicProxy upgrade in #1275.)
> Add regression test for interface with partial default implementation

- CHANGELOG.md
- src/Moq/StubbedPropertiesSetup.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Let `StubbedPropertiesSetup` figure out type parameter in a less fragile way

- CHANGELOG.md
- src/Moq/Mock.cs
- src/Moq/Mock`1.cs
- tests/Moq.Tests/EventHandlersFixture.cs
Closes #1310.
```csharp
public interface IFoo
{
Func<TArg1, ..., TArgN, Task> Bar;  // Func<..., ValueTask> is supported too
}
var mock = new Mock<IFoo>();
// subscribe an async event handler to the event:
mock.Object.Bar += async (arg1, ..., argN) => ...;
// raise the event and await completion of all async event handlers:
await mock.RaiseAsync(m => m.Bar += null, arg1, ..., argN);
```
> Add `Mock<T>.RaiseAsync`

- src/Moq/Moq.csproj
It is recommended to use the SPDX license identifier for NuGet packages (if applicable) instead of license URLs or license files.
This PR removes *LicenseUrl* and adds *LicenseExpression* from the package-related properties in *Moq.csproj* to follow this recommendation.
In order to keep the list of copyright holders linked to the NuGet package, the 'Copyright' property is added with the copyright holders as listed in current *License.txt*.
References:
https://docs.microsoft.com/en-us/nuget/reference/nuspec#license
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#important-nuget-package-metadata
https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg-(Technical-Spec)#license-expression-pack
> Use PackageLicenseExpression instead of PackageLicenseUrl

- CHANGELOG.md
- src/Moq/Protected/ProtectedMock.cs
- tests/Moq.Tests/Regressions/IssueReportsFixture.cs
> Don't throw away generic type arguments in one `mock.Protected().Verify<T>()` method overload

- Moq.sln
- src/Moq.CodeAnalysis/Moq.CodeAnalysis.csproj
- src/Moq.CodeAnalysis/Properties/Resources.es.resx
- src/Moq.CodeAnalysis/Properties/Resources.resx
- src/Moq.CodeAnalysis/SponsorLinker.cs
- src/Moq/Moq.csproj
See https://www.cazzulino.com/sponsorlink.html and https://github.com/devlooped/SponsorLink
Let's thank everyone who supports the project 💜
> Add 💜 SponsorLink support

- src/Moq/Moq.csproj
> Remove SponsorLink since it breaks MacOS restore

- src/Moq/Extensions.cs
> Improve performance for mocking interfaces: Cache GetInterfaceMap

- CHANGELOG.md
At present, the changelog.yml workflow isn't running successfully to completion (see https://github.com/moq/moq/actions/runs/5836450586/job/16054293256), so manually copy over the markdown from the past few releases for transparency.
Fixes #1406
> Manually update CHANGELOG.md for now

- src/Moq/ReturnsExtensions.cs
As discussed in #1419 this pull request aims to enhance the readability of the `GetDelay()` method by replacing the negation operator `!` with `>=`.
> A minor negation in GetDelay to make it more readable #1419

- License.txt
SPDX is the standard for describing software composition and its identifiers are used widely for automatic recognition of licenses (GitHub included).
> Update License.txt to use SPDX identifier for automatic recognition

- src/Moq.Tests/MatchersFixture.cs
#1483
Minor fix.
The second parameter of `Enumberable.Range` should be the count, not the end number.
> Fix semantic error in MatchersFixture.cs test

- src/Moq/Mock.cs
This was an unintended addition.
Fixes #1513
> Remove unused attribute

- src/Moq.Tests/MockFixture.cs
- src/Moq/Mock`1.cs
Updated ctor params to support nullable reference or a nullable item in the array. Added nullable preprocessor directive in unit tests
Closes #1494
> Updated ctor params to support nullable args 

- src/Moq/Interception/CastleProxyFactory.cs
When mocking many large classes across multiple assemblies causes a huge performance slow down as more classes get mocked. The AbstractTypeEmitter::CreateType in Castle.Core gets slower for each method on each class over time. Seeing up to 10 times slower as more and more classes get mocked.
By having a ProxyGenerator for each namespace it means less data in each ProxyGenerator and faster loading. 
In my test case the large classes each had ~400 methods and there were 100s of these classes all being mocked across all the tests. Test time went from 6 min down to 30 seconds with this change.
> Performance improvement for Mocking many large classes

- src/Moq/Async/AwaitableFactory.cs
- src/Moq/ExpressionExtensions.cs
Returning `IAwaitableFactory?` in [AwaitableFactory.cs](https://github.com/devlooped/moq/blob/95c4344ad089d3f4c5a629270f5fdc63480acdb4/src/Moq/Async/AwaitableFactory.cs#L33) file's `TryGet` method, in order to fix #1533.
> Minor enhancement to avoid null exceptions
