Source/Mock.cs
UnitTests/StubExtensionsFixture.cs

Fixed infinite loop when calling SetupAllPropertis for entities with the hierarchy. Written test StubsAllCyrcularDependency

Fixed infinite loop when calling SetupAllPropertis

---

Moq.nuspec
README.md
Source.NetCore/Moq.NetCore.csproj
Source.NetCore/project.json
Source/Capture.cs
Source/CaptureMatch.cs
Source/Extensions.cs
Source/Match.cs
Source/Mock.cs
Source/Moq.csproj
UnitTests.NetCore/ClassLibrary1/project.json
UnitTests.NetCore/Moq.NetCore.Tests/project.json
UnitTests/CaptureFixture.cs
UnitTests/CaptureMatchFixture.cs
UnitTests/Moq.Tests.csproj
UnitTests/VerifyFixture.cs
wrap/Moq/project.json

Upgrade to Castle.Core v4.0.0-beta1.

Upgrade Castle.Core dependency to v4.0.0-beta1.

---

Source/Matchers/ExpressionMatcher.cs

Simplify logic in `ExpressionMatcher.Matches`

---

Moq.VisualBasicTests/project.json
Source/Moq.NetCore.csproj
Source/project.json
UnitTests/Moq.NetCore.Tests.csproj
UnitTests/project.json

(Some Microsoft / `System` packages are also updated to current versions in order to avoid "package downgrade" warnings.)
This fixes #235.

Update Castle Core from version 4.0.0 to 4.1.0

---

Source/MethodCall.cs
UnitTests/Regressions/IssueReportsFixture.cs

Prevent stack overflow in conditional setups

---

Moq.VisualBasicTests/project.json
Moq.nuspec
Source/Moq.NetCore.csproj
Source/project.json
UnitTests/Moq.NetCore.Tests.csproj
UnitTests/project.json

Update Castle.Core from version 4.1.0 to 4.1.1

---

CHANGELOG.md
Source/Protected/IProtectedMock.cs
Source/Protected/ProtectedMock.cs

Add `SetupSequence` method group for protected members

---

CHANGELOG.md
Moq.Tests/VerifyFixture.cs
Source/Extensions.cs
Source/Invocation.cs
Source/InvocationCollection.cs
Source/Mock.Generic.cs
Source/Mock.cs
Source/MockException.cs
Source/Properties/Resources.Designer.cs
Source/Properties/Resources.resx

Add `Mock<T>.VerifyNoOtherCalls()` method

---

CHANGELOG.md
Moq.Tests/EmptyDefaultValueProviderFixture.cs
Moq.Tests/LookupOrFallbackDefaultValueProviderFixture.cs
Moq.Tests/MockDefaultValueProviderFixture.cs
Moq.Tests/Moq.Tests.csproj
Source/LookupOrFallbackDefaultValueProvider.cs
Source/Moq.csproj

Add C# 7 tuple support for `DefaultValue.Empty` and `DefaultValue.Mock`

---

CHANGELOG.md
Source/SequenceExtensions.cs

Add missing async methods for sequential setups on ValueTask<>

---

CHANGELOG.md
Moq.Tests/Moq.Tests.csproj
Moq.nuspec
Source/Moq.csproj

Update Castle.Core to version 4.3.1

---

src/Moq/Mock.cs

Add nDoc remark for SetReturnsDefault behaviour

---

CHANGELOG.md
build/xUnit.props
src/Moq/Moq.csproj
src/Moq/Moq.nuspec
tests/Moq.Tests.FSharpTypes/Moq.Tests.FSharpTypes.fsproj
tests/Moq.Tests/Moq.Tests.csproj

(Except for the GitInfo and SourceLink packages used in the build script. We'll deal with these later.)

Upgrade NuGet dependencies to current versions

---

CHANGELOG.md
tests/Moq.Tests/Regressions/IssueReportsFixture.cs

Add fixed test case to regression test suite

---

CONTRIBUTING.md
Moq.sln

(See it rendered [over at my fork](https://github.com/stakx/moq4/blob/contributing/CONTRIBUTING.md).)

Create a `CONTRIBUTING.md`

---

tests/Moq.Tests/Regressions/IssueReportsFixture.cs

Add test from issue to regression test suite

---

src/Moq/SequenceExtensions.cs
tests/Moq.Tests/SequenceExtensionsFixture.cs

Add `sequenceSetup.ReturnsAsync(Func<T>)`

---

CHANGELOG.md
src/Moq/ExpressionExtensions.cs
src/Moq/Extensions.cs
src/Moq/Guard.cs
src/Moq/Linq/MockSetupsBuilder.cs
src/Moq/Mock.cs
src/Moq/Protected/ProtectedAsMock.cs
src/Moq/Protected/ProtectedMock.cs
tests/Moq.Tests/StubExtensionsFixture.cs

Fix `SetupProperty` for partially overridden properties

---

CHANGELOG.md
src/Moq/Mock.cs
src/Moq/Times.cs
tests/Moq.Tests/TimesFixture.cs

Add `Times.Validate(count)` & `Times.ToString()`

---

CHANGELOG.md
src/Moq/Interception/InterceptionAspects.cs
src/Moq/Mock.cs
tests/Moq.Tests/Regressions/IssueReportsFixture.cs

Mark setups resulting from `DefaultValue.Mock` as matched

---

appveyor.yml
tests/Moq.Tests.FSharpTypes/Moq.Tests.FSharpTypes.fsproj
tests/Moq.Tests.VisualBasic/Moq.Tests.VisualBasic.vbproj
tests/Moq.Tests/Moq.Tests.csproj

(The current .NET Core target `netcoreapp2.2` was not an LTS release.)

Upgrade test projects to `netcoreapp3.1`

---

build/SourceLink.props

Update SourceLink build package to 1.0.0

---

.github/workflows/dotnet-file.yml
.github/workflows/includes.yml
.netconfig
README.md
sponsors.md

The upstream [sponsors.md](https://github.com/devlooped/sponsors/blob/main/sponsors.md), which is automatically updated, is sync'ed using [dotnet-file](https://github.com/devlooped/dotnet-file).
Whenever a PR that merges updates from dotnet-file ends up updating that file, the new `` in the readme will be picked up by the (also dotnet-file sync'ed) includes.yml workflow which uses [actions-includes](https://github.com/devlooped/actions-includes) which does the automated replacements.

Update and maintain list of sponsors automatically

---

.github/workflows/build.yml
.github/workflows/os-matrix.json
.github/workflows/publish.yml
.netconfig

- We don't push just from ubuntu anymore https://github.com/devlooped/oss/commit/7ec9101
- Simplify testing by switching to dotnet-retest https://github.com/devlooped/oss/commit/b5bb972

⬆️ Bump files with dotnet-file sync

---

src/Moq/Language/IVerifies.cs

Updated IVerifies.Verifiable method documentation code example
